# Original Author -> Harry Yang (taketoday@foxmail.com) https://taketoday.cn
# Copyright @ Harry Yang & 2023 All Rights Reserved.
#
# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER
########################################################

app:
  name: netty-app-demo

infra:
  output:
    ansi:
      enabled: always
  profiles:
    active: dev

logging:
  level:
    web: trace
    root: info