[[integration-testing-annotations-standard]]
= 标准注解支持

以下注解在 Infra TestContext 框架的所有配置中都支持标准语义。
请注意，这些注解并非特定于测试，可以在 TODAY Framework 中的任何位置使用。

* `@Autowired`
* `@Qualifier`
* `@Value`
* `@Resource` (jakarta.annotation) 如果存在 JSR-250
* `@ManagedBean` (jakarta.annotation) 如果存在 JSR-250
* `@Inject` (jakarta.inject) 如果存在 JSR-330
* `@Named` (jakarta.inject) 如果存在 JSR-330
* `@PersistenceContext` (jakarta.persistence) 如果存在 JPA
* `@PersistenceUnit` (jakarta.persistence) 如果存在 JPA
* `@Transactional` (infra.transaction.annotation)
  _具有 xref:testing/testcontext-framework/tx.adoc#testcontext-tx-attribute-support[有限的属性支持]_

.JSR-250 生命周期注解
[NOTE]
====
在 Infra TestContext 框架中，您可以在 `ApplicationContext` 中配置的任何应用程序组件上使用具有标准语义的 `@PostConstruct` 和 `@PreDestroy`。
但是，这些生命周期注解在实际测试类中的使用有限。

如果测试类中的方法使用 `@PostConstruct` 进行了注解，则该方法在底层测试框架的任何 before 方法（例如使用 JUnit Jupiter 的 `@BeforeEach` 注解的方法）之前运行，并且这适用于测试类中的每个测试方法。
另一方面，如果测试类中的方法使用 `@PreDestroy` 进行了注解，则该方法永远不会运行。
因此，在测试类中，我们建议您使用底层测试框架的测试生命周期回调，而不是 `@PostConstruct` 和 `@PreDestroy`。
====
