---
exclude_paths:
  - "**.js"
  - "**.css"
  - "**.html"
  - "**.xml"
  - "**.json"
  - "**.properties"
  - "**.md"
  - "**.adoc"
  - "**.gradle"
  - "**/test/**/*"
  - "**/buildSrc/**/*"
  - "**/testFixtures/**/*"
  - "today-test/src/main/java/infra/mock/**/*"