[[jdbc-embedded-database-support]]
= 嵌入式数据库支持

`infra.jdbc.datasource.embedded` 包提供了对嵌入式 Java 数据库引擎的支持。原生支持 https://www.hsqldb.org[HSQL]、https://www.h2database.com[H2] 和 https://db.apache.org/derby[Derby]。您还可以使用可扩展的 API 插入新的嵌入式数据库类型和 `DataSource` 实现。

[[jdbc-why-embedded-database]]
== 为什么要使用嵌入式数据库？

嵌入式数据库由于其轻量级的性质，在项目的开发阶段非常有用。好处包括易于配置、启动时间快、可测试性以及在开发过程中快速演进 SQL 的能力。


[[jdbc-embedded-database]]
== 创建嵌入式数据库

您可以将嵌入式数据库实例作为 bean 公开，如下例所示：

include-code::./JdbcEmbeddedDatabaseConfiguration[tag=snippet,indent=0]

[source,java]
----
@Configuration
public class JdbcEmbeddedDatabaseConfiguration {

  @Bean
  static DataSource dataSource() {
    return new EmbeddedDatabaseBuilder()
            .generateUniqueName(true)
            .setType(EmbeddedDatabaseType.H2)
            .addScripts("schema.sql", "test-data.sql")
            .build();
  }

}
----

前面的配置创建了一个嵌入式 H2 数据库，该数据库使用类路径根目录下的 `schema.sql` 和 `test-data.sql` 资源中的 SQL 进行填充。此外，作为最佳实践，为嵌入式数据库分配了一个唯一生成的名称。嵌入式数据库作为 `javax.sql.DataSource` 类型的 bean 提供给 Infra 容器，然后可以根据需要将其注入到数据访问对象中。

有关所有支持选项的更多详细信息，请参阅 {today-framework-api}/jdbc/datasource/embedded/EmbeddedDatabaseBuilder.html[`EmbeddedDatabaseBuilder` 的 javadoc]。


[[jdbc-embedded-database-types]]
== 选择嵌入式数据库类型

本节介绍如何选择 Infra 支持的三种嵌入式数据库之一。它包括以下主题：

* xref:data-access/jdbc/embedded-database-support.adoc#jdbc-embedded-database-using-HSQL[使用 HSQL]
* xref:data-access/jdbc/embedded-database-support.adoc#jdbc-embedded-database-using-H2[使用 H2]
* xref:data-access/jdbc/embedded-database-support.adoc#jdbc-embedded-database-using-Derby[使用 Derby]

[[jdbc-embedded-database-using-HSQL]]
=== 使用 HSQL

Infra 支持 HSQL 1.8.0 及更高版本。如果未显式指定类型，则 HSQL 是默认的嵌入式数据库。要显式指定 HSQL，请将 `embedded-database` 标签的 `type` 属性设置为 `HSQL`。如果您使用构建器 API，请使用 `EmbeddedDatabaseType.HSQL` 调用 `setType(EmbeddedDatabaseType)` 方法。

[[jdbc-embedded-database-using-H2]]
=== 使用 H2

Infra 支持 H2 数据库。要启用 H2，请将 `embedded-database` 标签的 `type` 属性设置为 `H2`。如果您使用构建器 API，请使用 `EmbeddedDatabaseType.H2` 调用 `setType(EmbeddedDatabaseType)` 方法。

[[jdbc-embedded-database-using-Derby]]
=== 使用 Derby

Infra 支持 Apache Derby 10.5 及更高版本。要启用 Derby，请将 `embedded-database` 标签的 `type` 属性设置为 `DERBY`。如果您使用构建器 API，请使用 `EmbeddedDatabaseType.DERBY` 调用 `setType(EmbeddedDatabaseType)` 方法。


[[jdbc-embedded-database-types-custom]]
== 自定义嵌入式数据库类型

虽然每种支持的类型都带有默认连接设置，但在必要时可以对其进行自定义。以下示例使用带有自定义驱动程序的 H2：

[tabs]
======
Java::
+
[source,java,indent=0,subs="verbatim,quotes",role="primary"]
----
@Configuration
public class DataSourceConfig {

  @Bean
  public DataSource dataSource() {
    return new EmbeddedDatabaseBuilder()
        .setDatabaseConfigurer(EmbeddedDatabaseConfigurers
            .customizeConfigurer(H2, this::customize))
            .addScript("schema.sql")
            .build();
  }

  private EmbeddedDatabaseConfigurer customize(EmbeddedDatabaseConfigurer defaultConfigurer) {
    return new EmbeddedDatabaseConfigurerDelegate(defaultConfigurer) {
      @Override
      public void configureConnectionProperties(ConnectionProperties properties, String databaseName) {
        super.configureConnectionProperties(properties, databaseName);
        properties.setDriverClass(CustomDriver.class);
      }
    };
  }
}
----

======


[[jdbc-embedded-database-dao-testing]]
== 使用嵌入式数据库测试数据访问逻辑

嵌入式数据库提供了一种轻量级的方法来测试数据访问代码。下一个示例是使用嵌入式数据库的数据访问集成测试模板。当嵌入式数据库不需要在测试类之间重用时，使用这样的模板对于一次性操作很有用。但是，如果您希望创建一个在测试套件中共享的嵌入式数据库，请考虑使用 xref:testing/testcontext-framework.adoc[Infra TestContext Framework]，并将嵌入式数据库配置为 Infra `ApplicationContext` 中的 bean，如 xref:data-access/jdbc/embedded-database-support.adoc#jdbc-embedded-database[创建嵌入式数据库] 中所述。以下清单显示了测试模板：

[tabs]
======
Java::
+
[source,java,indent=0,subs="verbatim,quotes",role="primary"]
----
public class DataAccessIntegrationTestTemplate {

  private EmbeddedDatabase db;

  @BeforeEach
  public void setUp() {
    // 创建一个从默认脚本填充的 HSQL 内存数据库
    // classpath:schema.sql 和 classpath:data.sql
    db = new EmbeddedDatabaseBuilder()
        .generateUniqueName(true)
        .addDefaultScripts()
        .build();
  }

  @Test
  public void testDataAccess() {
    JdbcTemplate template = new JdbcTemplate(db);
    template.query( /* ... */ );
  }

  @AfterEach
  public void tearDown() {
    db.shutdown();
  }

}
----

======


[[jdbc-embedded-database-unique-names]]
== Generating Unique Names for Embedded Databases

Development teams often encounter errors with embedded databases if their test suite
inadvertently attempts to recreate additional instances of the same database. This can
happen quite easily if an XML configuration file or `@Configuration` class is responsible
for creating an embedded database and the corresponding configuration is then reused
across multiple testing scenarios within the same test suite (that is, within the same JVM
process) -- for example, integration tests against embedded databases whose
`ApplicationContext` configuration differs only with regard to which bean definition
profiles are active.

The root cause of such errors is the fact that Infra `EmbeddedDatabaseFactory` (used
internally by both the `<jdbc:embedded-database>` XML namespace element and the
`EmbeddedDatabaseBuilder` for Java configuration) sets the name of the embedded database to
`testdb` if not otherwise specified. For the case of `<jdbc:embedded-database>`, the
embedded database is typically assigned a name equal to the bean's `id` (often,
something like `dataSource`). Thus, subsequent attempts to create an embedded database
do not result in a new database. Instead, the same JDBC connection URL is reused,
and attempts to create a new embedded database actually point to an existing
embedded database created from the same configuration.

To address this common issue, TODAY Framework 4.0 provides support for generating
unique names for embedded databases. To enable the use of generated names, use one of
the following options.

* `EmbeddedDatabaseFactory.setGenerateUniqueDatabaseName()`
* `EmbeddedDatabaseBuilder.generateUniqueName()`
* `<jdbc:embedded-database generate-name="true" ... >`


[[jdbc-embedded-database-extension]]
== Extending the Embedded Database Support

You can extend Infra JDBC embedded database support in two ways:

* Implement `EmbeddedDatabaseConfigurer` to support a new embedded database type.
* Implement `DataSourceFactory` to support a new `DataSource` implementation, such as a
connection pool to manage embedded database connections.

We encourage you to contribute extensions to the Infra community at
{today-framework-issues}[GitHub Issues].

