[[jdbc-object]]
= 将 JDBC 操作建模为 Java 对象

`infra.jdbc.object` 包包含允许您以更面向对象的方式访问数据库的类。例如，您可以运行查询并将结果作为包含业务对象的列表返回，其中关系列数据映射到业务对象的属性。您还可以运行存储过程并运行更新、删除和插入语句。

[NOTE]
====
许多 Infra 开发人员认为，下面描述的各种 RDBMS 操作类（xref:data-access/jdbc/object.adoc#jdbc-StoredProcedure[`StoredProcedure`] 类除外）通常可以用直接的 `JdbcTemplate` 调用代替。通常，编写直接调用 `JdbcTemplate` 方法的 DAO 方法（而不是将查询封装为完整的类）更简单。

但是，如果您从使用 RDBMS 操作类中获得了可衡量的价值，则应继续使用这些类。
====


[[jdbc-SqlQuery]]
== 理解 `SqlQuery`

`SqlQuery` 是一个可重用的、线程安全的类，它封装了一个 SQL 查询。子类必须实现 `newRowMapper(..)` 方法以提供一个 `RowMapper` 实例，该实例可以在迭代查询执行期间创建的 `ResultSet` 时每行创建一个对象。`SqlQuery` 类很少直接使用，因为 `MappingSqlQuery` 子类为将行映射到 Java 类提供了更方便的实现。扩展 `SqlQuery` 的其他实现包括 `MappingSqlQueryWithParameters` 和 `UpdatableSqlQuery`。


[[jdbc-MappingSqlQuery]]
== 使用 `MappingSqlQuery`

`MappingSqlQuery` 是一个可重用的查询，其中具体子类必须实现抽象的 `mapRow(..)` 方法，将提供的 `ResultSet` 的每一行转换为指定类型的对象。以下示例显示了一个自定义查询，该查询将 `t_actor` 关系中的数据映射到 `Actor` 类的实例：

[tabs]
======
Java::
+
[source,java,indent=0,subs="verbatim,quotes",role="primary"]
----
public class ActorMappingQuery extends MappingSqlQuery<Actor> {

  public ActorMappingQuery(DataSource ds) {
    super(ds, "select id, first_name, last_name from t_actor where id = ?");
    declareParameter(new SqlParameter("id", Types.INTEGER));
    compile();
  }

  @Override
  protected Actor mapRow(ResultSet rs, int rowNumber) throws SQLException {
    Actor actor = new Actor();
    actor.setId(rs.getLong("id"));
    actor.setFirstName(rs.getString("first_name"));
    actor.setLastName(rs.getString("last_name"));
    return actor;
  }
}
----

======

该类扩展了以 `Actor` 类型参数化的 `MappingSqlQuery`。此客户查询的构造函数将 `DataSource` 作为唯一参数。在此构造函数中，您可以使用 `DataSource` 和应运行以检索此查询的行的 SQL 调用超类上的构造函数。此 SQL 用于创建 `PreparedStatement`，因此它可能包含要在执行期间传入的任何参数的占位符。您必须使用传入 `SqlParameter` 的 `declareParameter` 方法声明每个参数。`SqlParameter` 接受一个名称和 `java.sql.Types` 中定义的 JDBC 类型。定义所有参数后，您可以调用 `compile()` 方法，以便可以准备并稍后运行该语句。此类在编译后是线程安全的，因此，只要在初始化 DAO 时创建这些实例，就可以将它们保留为实例变量并重复使用。以下示例显示了如何定义此类：

[tabs]
======
Java::
+
[source,java,indent=0,subs="verbatim,quotes",role="primary"]
----
private ActorMappingQuery actorMappingQuery;

@Autowired
public void setDataSource(DataSource dataSource) {
  this.actorMappingQuery = new ActorMappingQuery(dataSource);
}

public Customer getCustomer(Long id) {
  return actorMappingQuery.findObject(id);
}
----
======

前面示例中的方法检索具有作为唯一参数传入的 `id` 的客户。由于我们只希望返回一个对象，因此我们调用以 `id` 为参数的 `findObject` 便捷方法。相反，如果我们有一个返回对象列表并接受其他参数的查询，我们将使用接受作为可变参数传入的参数值数组的 `execute` 方法之一。以下示例显示了这种方法：

[tabs]
======
Java::
+
[source,java,indent=0,subs="verbatim,quotes",role="primary"]
----
public List<Actor> searchForActors(int age, String namePattern) {
  return actorSearchMappingQuery.execute(age, namePattern);
}
----

======


[[jdbc-SqlUpdate]]
== 使用 `SqlUpdate`

`SqlUpdate` 类封装了一个 SQL 更新。与查询一样，更新对象是可重用的，并且与所有 `RdbmsOperation` 类一样，更新可以具有参数并在 SQL 中定义。此类提供了许多类似于查询对象的 `execute(..)` 方法的 `update(..)` 方法。`SqlUpdate` 类是具体的。它可以被子类化——例如，添加自定义更新方法。但是，您不必子类化 `SqlUpdate` 类，因为它可以通过设置 SQL 和声明参数轻松参数化。以下示例创建了一个名为 `execute` 的自定义更新方法：

[tabs]
======
Java::
+
[source,java,indent=0,subs="verbatim,quotes",role="primary"]
----
import java.sql.Types;
import javax.sql.DataSource;
import infra.jdbc.core.SqlParameter;
import infra.jdbc.object.SqlUpdate;

public class UpdateCreditRating extends SqlUpdate {

  public UpdateCreditRating(DataSource ds) {
    setDataSource(ds);
    setSql("update customer set credit_rating = ? where id = ?");
    declareParameter(new SqlParameter("creditRating", Types.NUMERIC));
    declareParameter(new SqlParameter("id", Types.NUMERIC));
    compile();
  }

  /**
   * @param id for the Customer to be updated
   * @param rating the new value for credit rating
   * @return number of rows updated
   */
  public int execute(int id, int rating) {
    return update(rating, id);
  }
}
----
======


[[jdbc-StoredProcedure]]
== 使用 `StoredProcedure`

`StoredProcedure` 类是 RDBMS 存储过程的对象抽象的 `abstract` 超类。

继承的 `sql` 属性是 RDBMS 中存储过程的名称。

要为 `StoredProcedure` 类定义参数，可以使用 `SqlParameter` 或其子类之一。必须在构造函数中指定参数名称和 SQL 类型，如以下代码片段所示：

[tabs]
======
Java::
+
[source,java,indent=0,subs="verbatim,quotes",role="primary"]
----
new SqlParameter("in_id", Types.NUMERIC),
new SqlOutParameter("out_first_name", Types.VARCHAR),
----

======

SQL 类型使用 `java.sql.Types` 常量指定。

第一行（带有 `SqlParameter`）声明了一个 IN 参数。您可以将 IN 参数用于存储过程调用和使用 `SqlQuery` 及其子类的查询（在 xref:data-access/jdbc/object.adoc#jdbc-SqlQuery[理解 `SqlQuery`] 中介绍）。

第二行（带有 `SqlOutParameter`）声明了一个用于存储过程调用的 `out` 参数。还有一个用于 `InOut` 参数的 `SqlInOutParameter`。
