[[beans-binding]]
= 数据绑定

数据绑定（Data binding）用于将用户输入绑定到目标对象，其中用户输入是一个以属性路径为键的映射，遵循 xref:beans-beans-conventions[JavaBeans 约定]。
`DataBinder` 是支持这一功能的主要类，它提供了两种绑定用户输入的方式：

- xref:beans-constructor-binding[构造函数绑定] - 将用户输入绑定到公共数据构造函数，在用户输入中查找构造函数参数值。
- xref:beans-beans[属性绑定] - 将用户输入绑定到 Setter 方法，将用户输入中的键与目标对象结构的属性进行匹配。

您可以同时应用构造函数绑定和属性绑定，也可以只应用其中一种。


[[beans-constructor-binding]]
== 构造函数绑定

要使用构造函数绑定：

1. 创建一个目标对象为 `null` 的 `DataBinder`。
2. 将 `targetType` 设置为目标类。
3. 调用 `construct`。

目标类应具有单个公共构造函数或单个带参数的非公共构造函数。如果有多个构造函数，则使用默认构造函数（如果存在）。

默认情况下，使用构造函数参数名称来查找参数值，但您可以配置 `NameResolver`。Web MVC 和 WebFlux 都依赖于此，允许通过构造函数参数上的 `@BindParam` 注解来自定义要绑定的值的名称。

xref:beans-beans-conventions[类型转换] 会根据需要应用以转换用户输入。
如果构造函数参数是一个对象，则会以相同的方式递归构造，但通过嵌套属性路径。这意味着构造函数绑定会创建目标对象及其包含的任何对象。

绑定和转换错误反映在 `DataBinder` 的 `BindingResult` 中。
如果目标创建成功，则在调用 `construct` 后，`target` 将设置为创建的实例。




[[beans-beans]]
== 使用 `BeanWrapper` 进行属性绑定

`infra.beans` 包遵循 JavaBeans 标准。
JavaBean 是一个具有默认无参构造函数的类，并遵循命名约定，例如（举例来说）名为 `bingoMadness` 的属性将具有 setter 方法 `setBingoMadness(..)` 和 getter 方法 `getBingoMadness()`。有关 JavaBeans 和规范的更多信息，请参阅 {java-api}/java.desktop/java/beans/package-summary.html[javabeans]。

beans 包中一个非常重要的类是 `BeanWrapper` 接口及其相应的实现（`BeanWrapperImpl`）。正如 Javadoc 中所述，`BeanWrapper` 提供了设置和获取属性值（单独或批量）、获取属性描述符以及查询属性以确定它们是可读还是可写的功能。此外，`BeanWrapper` 还支持嵌套属性，允许将子属性的属性设置为无限深度。`BeanWrapper` 还支持添加标准 JavaBeans `PropertyChangeListeners` 和 `VetoableChangeListeners`，而无需在目标类中编写支持代码。
最后但并非最不重要的一点是，`BeanWrapper` 提供了对设置索引属性的支持。
`BeanWrapper` 通常不直接由应用程序代码使用，而是由 `DataBinder` 和 `BeanFactory` 使用。

`BeanWrapper` 的工作方式部分由其名称表明：它包装一个 bean 以对该 bean 执行操作，例如设置和检索属性。



[[beans-beans-conventions]]
=== 设置和获取基本及嵌套属性

设置和获取属性是通过 `BeanWrapper` 的 `setPropertyValue` 和 `getPropertyValue` 重载方法变体完成的。有关详细信息，请参阅其 Javadoc。下表显示了这些约定的一些示例：

[[beans-beans-conventions-properties-tbl]]
.属性示例
|===
| 表达式| 说明

| `name`
| 指示属性 `name`，对应于 `getName()` 或 `isName()` 和 `setName(..)` 方法。

| `account.name`
| 指示属性 `account` 的嵌套属性 `name`，对应于（例如）`getAccount().setName()` 或 `getAccount().getName()` 方法。

| `account[2]`
| 指示索引属性 `account` 的_第三个_元素。索引属性可以是 `array`、`list` 或其他自然排序的集合类型。

| `account[COMPANYNAME]`
| 指示由 `account` `Map` 属性的 `COMPANYNAME` 键索引的映射条目的值。
|===

（如果您不打算直接使用 `BeanWrapper`，则下一部分对您来说并不重要。如果您只使用 `DataBinder` 和 `BeanFactory` 及其默认实现，则应跳至 xref:core/validation/beans-beans.adoc#beans-beans-conversion[关于 `PropertyEditors` 的部分]。）

以下两个示例类使用 `BeanWrapper` 来获取和设置属性：

[tabs]
======
Java::
+
[source,java,indent=0,subs="verbatim,quotes",role="primary"]
----
public class Company {

  private String name;
  private Employee managingDirector;

  public String getName() {
    return this.name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Employee getManagingDirector() {
    return this.managingDirector;
  }

  public void setManagingDirector(Employee managingDirector) {
    this.managingDirector = managingDirector;
  }
}
----
======

[tabs]
======
Java::
+
[source,java,indent=0,subs="verbatim,quotes",role="primary"]
----
public class Employee {

  private String name;

  private float salary;

  public String getName() {
    return this.name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public float getSalary() {
    return salary;
  }

  public void setSalary(float salary) {
    this.salary = salary;
  }
}
----

======

以下代码片段显示了如何检索和操作实例化的 ``Company`` 和 ``Employee`` 的一些属性的示例：

[tabs]
======
Java::
+
[source,java,indent=0,subs="verbatim,quotes",role="primary"]
----
BeanWrapper company = new BeanWrapperImpl(new Company());
// 设置公司名称..
company.setPropertyValue("name", "Some Company Inc.");
// ... 也可以这样做：
PropertyValue value = new PropertyValue("name", "Some Company Inc.");
company.setPropertyValue(value);

// 好的，让我们创建主管并将其与公司绑定：
BeanWrapper jim = new BeanWrapperImpl(new Employee());
jim.setPropertyValue("name", "Jim Stravinsky");
company.setPropertyValue("managingDirector", jim.getWrappedInstance());

// 通过公司检索主管的薪水
Float salary = (Float) company.getPropertyValue("managingDirector.salary");
----
======



[[beans-beans-conversion]]
