[[beans-child-bean-definitions]]
= Bean 定义继承

一个bean定义可以包含大量的配置信息，包括构造函数参数、属性值以及容器特定的信息，
例如初始化方法、静态工厂方法名称等。子bean定义从父定义中继承配置数据。子定义可以根据需要覆盖一些值或添加其他值。
使用父子bean定义可以节省大量的输入。实际上，这是一种模板化形式。

如果你以编程方式使用 `ApplicationContext` 接口，子bean定义由 `ChildBeanDefinition` 类表示。
大多数用户不会在这个级别上使用它们。相反，他们在类似于 `ClassPathXmlApplicationContext` 的类中以声明方式配置 bean 定义。
当您使用基于XML的配置元数据时，可以通过使用 `parent` 属性来指示一个子bean定义，将父 bean 作为该属性的值。以下示例显示了如何这样做：

[source,xml,indent=0,subs="verbatim,quotes"]
----
<bean id="inheritedTestBean" abstract="true" class="cn.taketoday.beans.TestBean">
  <property name="name" value="parent"/>
  <property name="age" value="1"/>
</bean>

<bean id="inheritsWithDifferentClass" class="cn.taketoday.beans.DerivedTestBean"
    parent="inheritedTestBean" init-method="initialize">  <1>
  <property name="name" value="override"/>
  <!-- the age property value of 1 will be inherited from parent -->
</bean>
----
<1> Note the `parent` attribute.

一个子 bean 定义如果没有指定 bean 类，则使用父定义中的 bean 类，但也可以覆盖它。
在后一种情况下，子 bean 类必须与父类兼容（也就是说，它必须接受父类的属性值）。

子 bean 定义从父类继承范围、构造函数参数值、属性值和方法覆盖，可以选择添加新值。您指定的任何范围、初始化方法、销毁方法或static工厂方法设置都会覆盖相应的父设置。

其余设置始终来自子定义：`depends on`、自动装配模式、依赖项检查、单例和延迟初始化。

前面的示例通过使用abstract属性明确将父 bean 定义标记为抽象。如果父定义没有指定类，则需要显式将父 bean 定义标记为 `abstract`，如下例所示：

[source,xml,indent=0,subs="verbatim,quotes"]
----
<bean id="inheritedTestBeanWithoutClass" abstract="true">
  <property name="name" value="parent"/>
  <property name="age" value="1"/>
</bean>

<bean id="inheritsWithClass" class="cn.taketoday.beans.DerivedTestBean"
    parent="inheritedTestBeanWithoutClass" init-method="initialize">
  <property name="name" value="override"/>
  <!-- age will inherit the value of 1 from the parent bean definition-->
</bean>
----

父 bean 不能独立实例化，因为它是不完整的，而且明确标记为 `abstract`。当一个定义是 `abstract` 时，
它只能作为一个纯模板 bean 定义使用，作为子定义的父定义。尝试单独使用这样的 `abstract` 父 bean，
通过将其作为另一个 bean 的 ref 属性引用或使用显式的 `getBean()` 调用与父 bean ID 返回错误。
同样，容器的内部 `preInstantiateSingletons()` 方法会忽略被定义为抽象的 bean 定义。


NOTE: `ApplicationContext` 默认情况下会预先实例化所有单例。因此，对于单例 bean，
如果你有一个（父）bean 定义，你只打算将其用作模板，并且这个定义指定了一个类，
你必须确保将 __abstract__ 属性设置为 `true`，否则应用上下文实际上（尝试）会预先实例化抽象 bean。

