[[infra-testing-annotation-testexecutionlisteners]]
= `@TestExecutionListeners`

`@TestExecutionListeners` 用于为特定测试类、其子类及其嵌套类注册监听器。如果你希望全局注册监听器，应通过 xref:testing/testcontext-framework/tel-config.adoc[`TestExecutionListener` 配置] 中描述的自动发现机制进行注册。

以下示例展示了如何注册两个 `TestExecutionListener` 实现：

[tabs]
======
Java::
+
[source,java,indent=0,subs="verbatim,quotes",role="primary"]
----
@ContextConfiguration
@TestExecutionListeners({CustomTestExecutionListener.class, AnotherTestExecutionListener.class}) // <1>
class CustomTestExecutionListenerTests {
  // class body...
}
----
<1> 注册两个 `TestExecutionListener` 实现。

======


默认情况下，`@TestExecutionListeners` 支持从超类或封闭类继承监听器。有关示例和更多详细信息，请参见 xref:testing/testcontext-framework/support-classes.adoc#testcontext-junit-jupiter-nested-test-configuration[`@Nested` 测试类配置] 和 {today-framework-api}/test/context/TestExecutionListeners.html[`@TestExecutionListeners` javadoc]。如果你发现需要切换回使用默认的 `TestExecutionListener` 实现，请参见 xref:testing/testcontext-framework/tel-config.adoc#testcontext-tel-config-registering-tels[注册 `TestExecutionListener` 实现] 中的说明。
