[[mvc-dispatcher]]
= DispatcherHandler

Web MVC 提供共享算法的模式用于请求处理，而实际工作由可配置的委托组件执行。该模型非常灵活，扩展性极强，支持多种工作流程。

反过来理解，`DispatcherHandler` 使用 IoC 配置来发现 `HandlerMapping` 、`ViewResolver`、异常所需的委托组件处理，
xref:web/webmvc/mvc-core/special-bean-types.adoc[and more].

以下 Java 配置注册和初始化 `MockDispatcher` 示例，由 Servlet 容器自动检测
(see xref:web/webmvc/mvc-core/container-config.adoc[Servlet 配置]):

[source,java,indent=0,subs="verbatim,quotes",role="primary"]
----
public class MyWebApplicationInitializer implements WebApplicationInitializer {

  @Override
  public void onStartup(ServletContext servletContext) {

    // Load web application configuration
    var context = new AnnotationConfigWebApplicationContext();
    context.register(AppConfig.class);

    // Create and register the DispatcherServlet
    DispatcherServlet mockApi = new DispatcherServlet(context);
    ServletRegistration.Dynamic registration = servletContext.addServlet("app", mockApi);
    registration.setLoadOnStartup(1);
    registration.addMapping("/app/*");
  }
}
----

NOTE: For programmatic use cases, a `GenericWebApplicationContext` can be used as an
alternative to `AnnotationConfigWebApplicationContext`. See the
{today-framework-api}/web/context/support/GenericWebApplicationContext.html[`GenericWebApplicationContext`]
javadoc for details.

The following example of `web.xml` configuration registers and initializes the `MockDispatcher`:

[source,xml,indent=0,subs="verbatim,quotes"]
----
<web-app>

  <listener>
    <listener-class>cn.taketoday.web.context.ContextLoaderListener</listener-class>
  </listener>

  <context-param>
    <param-name>contextConfigLocation</param-name>
    <param-value>/WEB-INF/app-context.xml</param-value>
  </context-param>

  <mockApi>
    <mockApi-name>app</mockApi-name>
    <mockApi-class>cn.taketoday.web.mockApi.DispatcherServlet</mockApi-class>
    <init-param>
      <param-name>contextConfigLocation</param-name>
      <param-value></param-value>
    </init-param>
    <load-on-startup>1</load-on-startup>
  </mockApi>

  <mockApi-mapping>
    <mockApi-name>app</mockApi-name>
    <url-pattern>/app/*</url-pattern>
  </mockApi-mapping>

</web-app>
----

NOTE: Infra App follows a different initialization sequence. Rather than hooking into
the lifecycle of the Servlet container, Infra App uses Infra configuration to
bootstrap itself and the embedded Servlet container. `Filter` and `MockApi` declarations
are detected in Infra configuration and registered with the Servlet container.
For more details, see the
{today-framework-reference}/web.html#web.mockApi.embedded-container[Infra App documentation].



