[[mvc-ann-initbinder]]
= `@InitBinder`

`@Controller` 或 `@ControllerAdvice` 类可以有 `@InitBinder` 方法来初始化 `WebDataBinder` 实例，这些实例可以：

* 将请求参数绑定到模型对象。
* 将请求值从字符串转换为对象属性类型。
* 在呈现 HTML 表单时将模型对象属性格式化为字符串。

在 `@Controller` 中，`DataBinder` 自定义应用于控制器内的局部，或者甚至通过注解引用名称来应用于特定的模型属性。
在 `@ControllerAdvice` 中，自定义可以应用于所有或控制器的一个子集。

您可以在 `DataBinder` 中注册 `PropertyEditor`、`Converter` 和 `Formatter` 组件进行类型转换。
或者，您可以使用 xref:web/webmvc/mvc-config/conversion.adoc[MVC 配置] 在全局共享的 `FormattingConversionService`
中注册 `Converter` 和 `Formatter` 组件。

`@InitBinder` 方法可以具有许多与 `@RequestMapping` 方法相同的参数，显著的例外是 `@ModelAttribute`。
通常，这些方法具有一个 `WebDataBinder` 参数（用于注册）和一个 `void` 返回值，例如：


[source,java,indent=0,subs="verbatim,quotes",role="primary"]
----
@Controller
public class FormController {

  @InitBinder // <1>
  public void initBinder(WebDataBinder binder) {
    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
    dateFormat.setLenient(false);
    binder.registerCustomEditor(Date.class, new CustomDateEditor(dateFormat, false));
  }

  // ...
}
----
<1> 定义一个 `@InitBinder` 方法。

或者，当您通过共享的 `FormattingConversionService` 使用基于 `Formatter` 的设置时，
您可以重复使用相同的方法并注册特定于控制器的 `Formatter` 实现，如下例所示：


[source,java,indent=0,subs="verbatim,quotes",role="primary"]
----
@Controller
public class FormController {

  @InitBinder
  protected void initBinder(WebDataBinder binder) {
    binder.addCustomFormatter(new DateFormatter("yyyy-MM-dd"));
  }

  // ...
}
----

[[mvc-ann-initbinder-model-design]]
== Model 设计

include::partial$web/web-data-binding-model-design.adoc[]


