antora:
  extensions:
  - '@antora/collector-extension'
  - id: '@antora/atlas-extension'
    require: '@antora/atlas-extension'
    enabled: false
  - '@today-tech/antora-extensions/latest-version-extension'
  - require: '@today-tech/antora-extensions/root-component-extension'
    root_component_name: 'framework'
site:
  title: TODAY Framework Reference
content:
  sources:
  - url: ./..
    branches: HEAD
    start_path: infra-docs
    worktrees: true
asciidoc:
  attributes:
    page-stackoverflow-url: https://stackoverflow.com/questions/tagged/today-infra
    hide-uri-scheme: '@'
    page-pagination: ''
    primary-site-url: https://docs.today-tech.cn/today-infrastructure/reference
    tabs-sync-option: '@'
  extensions:
  - '@asciidoctor/tabs'
  sourcemap: true
urls:
  latest_version_segment: ''
  redirect_facility: httpd
runtime:
  log:
    failure_level: warn
ui:
  bundle:
    url: https://github.com/today-tech/antora-ui/releases/download/latest/ui-bundle.zip?v=1
    snapshot: true
