[[mvc-test-server-htmlunit-geb]]
= MockMvc 和 Geb

在上一节中，我们看到了如何将 MockMvc 与 WebDriver 结合使用。在本节中，我们使用 https://www.gebish.org/[Geb] 让我们的测试更具 Groovy 风格。

[[mvc-test-server-htmlunit-geb-why]]
== 为什么选择 Geb 和 MockMvc？

Geb 由 WebDriver 支持，因此它提供了许多我们从 WebDriver 获得的 xref:testing/mvc-test-framework/server-htmlunit/webdriver.adoc#mvc-test-server-htmlunit-webdriver-why[相同好处]。然而，Geb 通过为我们处理一些样板代码，让事情变得更加容易。

[[mvc-test-server-htmlunit-geb-setup]]
== MockMvc 和 Geb 设置

我们可以轻松地使用一个使用 MockMvc 的 Selenium WebDriver 初始化一个 Geb `Browser`，如下所示：

[source,groovy]
----
def setup() {
	browser.driver = MockMvcHtmlUnitDriverBuilder
		.webAppContextSetup(context)
		.build()
}
----

NOTE: 这是使用 `MockMvcHtmlUnitDriverBuilder` 的一个简单示例。有关更高级的用法，请参阅 xref:testing/mvc-test-framework/server-htmlunit/webdriver.adoc#mvc-test-server-htmlunit-webdriver-advanced-builder[高级 `MockMvcHtmlUnitDriverBuilder`]。

这确保了任何引用 `localhost` 作为服务器的 URL 都会被定向到我们的 `MockMvc` 实例，而无需真正的 HTTP 连接。任何其他 URL 都会像往常一样使用网络连接请求。这让我们能够轻松测试 CDN 的使用。

[[mvc-test-server-htmlunit-geb-usage]]
== MockMvc 和 Geb 用法

现在我们可以像平常一样使用 Geb，而无需将应用程序部署到 Servlet 容器。例如，我们可以请求创建消息的视图，如下所示：

[source,groovy]
----
to CreateMessagePage
----

然后我们可以填写表单并提交以创建消息，如下所示：

[source,groovy]
----
when:
form.summary = expectedSummary
form.text = expectedMessage
submit.click(ViewMessagePage)
----

任何无法识别的方法调用、属性访问或未找到的引用都会转发到当前页面对象。这消除了我们直接使用 WebDriver 时所需的大量样板代码。

与直接使用 WebDriver 一样，通过使用 Page Object 模式，这改进了我们的 xref:testing/mvc-test-framework/server-htmlunit/mah.adoc#mvc-test-server-htmlunit-mah-usage[HtmlUnit 测试] 的设计。如前所述，我们可以将 Page Object 模式与 HtmlUnit 和 WebDriver 一起使用，但在 Geb 中更容易。考虑我们新的基于 Groovy 的 `CreateMessagePage` 实现：

[source,groovy]
----
class CreateMessagePage extends Page {
	static url = 'messages/form'
	static at = { assert title == 'Messages : Create'; true }
	static content =  {
		submit { $('input[type=submit]') }
		form { $('form') }
		errors(required:false) { $('label.error, .alert-error')?.text() }
	}
}
----

我们的 `CreateMessagePage` 扩展了 `Page`。我们不详细介绍 `Page`，但总而言之，它包含我们所有页面的通用功能。我们定义了一个可以找到此页面的 URL。这让我们能够导航到该页面，如下所示：

[source,groovy]
----
to CreateMessagePage
----

我们还有一个 `at` 闭包，用于确定我们是否在指定的页面。如果我们位于正确的页面，它应该返回 `true`。这就是为什么我们可以断言我们位于正确的页面，如下所示：

[source,groovy]
----
then:
at CreateMessagePage
errors.contains('This field is required.')
----

NOTE: 我们在闭包中使用断言，以便如果我们位于错误的页面，我们可以确定哪里出了问题。

接下来，我们创建一个 `content` 闭包，指定页面内所有感兴趣的区域。我们可以使用 https://www.gebish.org/manual/current/#the-jquery-ish-navigator-api[jQuery 风格的 Navigator API] 来选择我们感兴趣的内容。

最后，我们可以验证新消息是否成功创建，如下所示：

[source,groovy]
----
then:
at ViewMessagePage
success == 'Successfully created a new message'
id
date
summary == expectedSummary
message == expectedMessage
----

有关如何充分利用 Geb 的更多详细信息，请参阅 https://www.gebish.org/manual/current/[Geb 之书] 用户手册。
