[[orm-general]]
= 一般 ORM 集成注意事项

本节重点介绍适用于所有 ORM 技术的注意事项。
xref:data-access/orm/hibernate.adoc[Hibernate] 部分提供了更多详细信息，并在具体上下文中展示了这些功能和配置。

Infra ORM 集成的主要目标是清晰的应用程序分层（使用任何数据访问和事务技术）以及应用程序对象的松散耦合——业务服务不再依赖于数据访问或事务策略，不再有硬编码的资源查找，不再有难以替换的单例，不再有自定义服务注册表。目标是拥有一种简单且一致的方法来连接应用程序对象，使它们尽可能可重用且不受容器依赖项的影响。所有单独的数据访问功能都可以单独使用，但也可以很好地与 Infra 应用程序上下文概念集成，提供基于 XML 的配置和不需要感知 Infra 的普通 JavaBean 实例的交叉引用。在典型的 Infra 应用程序中，许多重要对象都是 JavaBean：数据访问模板、数据访问对象、事务管理器、使用数据访问对象和事务管理器的业务服务、Web 视图解析器、使用业务服务的 Web 控制器等等。


[[orm-resource-mngmnt]]
== 资源和事务管理

典型的业务应用程序充斥着重复的资源管理代码。
许多项目试图发明自己的解决方案，有时为了编程方便而牺牲了对故障的正确处理。Infra 提倡简单的解决方案来进行正确的资源处理，即在 JDBC 的情况下通过模板化进行 IoC，并为 ORM 技术应用 AOP 拦截器。

基础设施提供了正确的资源处理，并将特定 API 异常适当转换为未经检查的基础设施异常层次结构。Infra 引入了一个 DAO 异常层次结构，适用于任何数据访问策略。对于直接 JDBC，xref:data-access/jdbc/core.adoc#jdbc-JdbcTemplate[上一节] 中提到的 `JdbcTemplate` 类提供了连接处理以及将 `SQLException` 正确转换为 `DataAccessException` 层次结构的功能，包括将特定于数据库的 SQL 错误代码转换为有意义的异常类。对于 ORM 技术，请参阅 xref:data-access/orm/general.adoc#orm-exception-translation[下一节] 以了解如何获得相同的异常转换优势。

谈到事务管理，`JdbcTemplate` 类挂钩到 Infra 事务支持，并通过各自的 Infra 事务管理器支持 JTA 和 JDBC 事务。对于支持的 ORM 技术，Infra 通过 Hibernate 和 JPA 事务管理器以及 JTA 支持提供 Hibernate 和 JPA 支持。
有关事务支持的详细信息，请参阅 xref:data-access/transaction.adoc[事务管理] 章节。


[[orm-exception-translation]]
== 异常转换

当您在 DAO 中使用 Hibernate 或 JPA 时，您必须决定如何处理持久性技术的原生异常类。DAO 会抛出 `HibernateException` 或 `PersistenceException` 的子类，具体取决于技术。这些异常都是运行时异常，无需声明或捕获。您可能还需要处理 `IllegalArgumentException` 和 `IllegalStateException`。这意味着调用者只能将异常视为通常是致命的，除非他们想依赖于持久性技术本身的异常结构。如果不将调用者绑定到实现策略，就不可能捕获特定原因（例如乐观锁定失败）。
对于强烈基于 ORM 或不需要任何特殊异常处理（或两者兼而有之）的应用程序，这种权衡可能是可以接受的。但是，Infra 允许通过 `@Repository` 注解透明地应用异常转换。以下示例（一个用于 Java 配置，一个用于 XML 配置）显示了如何执行此操作：

[tabs]
======
Java::
+
[source,java,indent=0,subs="verbatim,quotes",role="primary"]
----
@Repository
public class ProductDaoImpl implements ProductDao {

  // 类体...

}
----
======

[source,xml,indent=0,subs="verbatim,quotes"]
----
<beans>

  <!-- 异常转换 bean 后处理器 -->
  <bean class="infra.dao.annotation.PersistenceExceptionTranslationPostProcessor"/>

  <bean id="myProductDao" class="product.ProductDaoImpl"/>

</beans>
----

后处理器会自动查找所有异常转换器（`PersistenceExceptionTranslator` 接口的实现），并通知所有标记有 `@Repository` 注解的 bean，以便发现的转换器可以拦截并在抛出的异常上应用适当的转换。

总之，您可以基于普通持久性技术的 API 和注解实现 DAO，同时仍然受益于 Infra 管理的事务、依赖注入和透明的异常转换（如果需要）到 Infra 自定义异常层次结构。
