[[mvc-config-message-converters]]
= 消息转换器

您可以通过重写 {today-framework-api}/web/config/WebMvcConfigurer.html#configureMessageConverters-java.util.List-[`configureMessageConverters()`]，
在Java配置中设置要使用的 `HttpMessageConverter` 实例，替换默认使用的实例。您也可以通过重写
{today-framework-api}/web/config/WebMvcConfigurer.html#extendMessageConverters-java.util.List-[`extendMessageConverters()`]，
在最后定制配置的消息转换器列表。

TIP: 在 Infra App 应用程序中，`WebMvcAutoConfiguration` 除了默认转换器外，还会添加它检测到的任何
`HttpMessageConverter` Bean。或者，也可以使用 `extendMessageConverters` 在最后修改消息转换器。

以下示例添加了 XML 和 Jackson JSON 转换器，并使用自定义的 `ObjectMapper` 替换默认的转换器：

[source,java]
----
@Configuration
public class WebConfiguration implements WebMvcConfigurer {

  @Override
  public void configureMessageConverters(List<HttpMessageConverter<?>> converters) {
    Jackson2ObjectMapperBuilder builder = new Jackson2ObjectMapperBuilder()
            .indentOutput(true)
            .dateFormat(new SimpleDateFormat("yyyy-MM-dd"))
            .modulesToInstall(new ParameterNamesModule());
    converters.add(new MappingJackson2HttpMessageConverter(builder.build()));
    converters.add(new MappingJackson2XmlHttpMessageConverter(builder.createXmlMapper(true).build()));
  }
}
----

在前面的示例中，
{today-framework-api}/http/converter/json/Jackson2ObjectMapperBuilder.html[`Jackson2ObjectMapperBuilder`]
用于为 `MappingJackson2HttpMessageConverter` 和 `MappingJackson2XmlHttpMessageConverter` 创建一个通用配置，启用缩进，自定义日期格式，并注册
{jackson-github-org}/jackson-module-parameter-names[`jackson-module-parameter-names`]，
这增加了对访问参数名称的支持（Java 8 中新增的功能）。

此构建器按以下方式自定义 Jackson 的默认属性：

* {jackson-docs}/jackson-databind/javadoc/2.6/com/fasterxml/jackson/databind/DeserializationFeature.html#FAIL_ON_UNKNOWN_PROPERTIES[`DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES`] 被禁用。
* {jackson-docs}/jackson-databind/javadoc/2.6/com/fasterxml/jackson/databind/MapperFeature.html#DEFAULT_VIEW_INCLUSION[`MapperFeature.DEFAULT_VIEW_INCLUSION`] 被禁用。

它还自动注册以下知名模块（如果它们在类路径上被检测到）：

* {jackson-github-org}/jackson-datatype-joda[jackson-datatype-joda]: 支持 Joda-Time 类型。
* {jackson-github-org}/jackson-datatype-jsr310[jackson-datatype-jsr310]: 支持 Java 8 日期和时间 API 类型。
* {jackson-github-org}/jackson-datatype-jdk8[jackson-datatype-jdk8]: 支持其他 Java 8 类型，如 `Optional`。

注意：启用 Jackson XML 支持的缩进需要除了
https://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22org.codehaus.woodstox%22%20AND%20a%3A%22woodstox-core-asl%22[`woodstox-core-asl`]
依赖项外，还需要 https://search.maven.org/#search%7Cga%7C1%7Ca%3A%22jackson-dataformat-xml%22[`jackson-dataformat-xml`] 依赖项。

其他有趣的 Jackson 模块包括：

* https://github.com/zalando/jackson-datatype-money[jackson-datatype-money]: 支持 `javax.money` 类型（非官方模块）。
* {jackson-github-org}/jackson-datatype-hibernate[jackson-datatype-hibernate]: 支持 Hibernate 特定类型和属性（包括延迟加载方面）。
