// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sample.proto

package cn.taketoday.protobuf;

/**
 * Protobuf type {@code Msg}
 */
public final class Msg extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:Msg)
        MsgOrBuilder {
  private static final long serialVersionUID = 0L;

  // Use Msg.newBuilder() to construct.
  private Msg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }

  private Msg() {
    foo_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({ "unused" })
  protected java.lang.Object newInstance(
          UnusedPrivateParameter unused) {
    return new Msg();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }

  private Msg(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();
            bitField0_ |= 0x00000001;
            foo_ = s;
            break;
          }
          case 18: {
            cn.taketoday.protobuf.SecondMsg.Builder subBuilder = null;
            if (((bitField0_ & 0x00000002) != 0)) {
              subBuilder = blah_.toBuilder();
            }
            blah_ = input.readMessage(cn.taketoday.protobuf.SecondMsg.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(blah_);
              blah_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000002;
            break;
          }
          default: {
            if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    }
    catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    }
    catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
    }
    finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }

  public static final com.google.protobuf.Descriptors.Descriptor
  getDescriptor() {
    return cn.taketoday.protobuf.OuterSample.internal_static_Msg_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
  internalGetFieldAccessorTable() {
    return cn.taketoday.protobuf.OuterSample.internal_static_Msg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                    cn.taketoday.protobuf.Msg.class, cn.taketoday.protobuf.Msg.Builder.class);
  }

  private int bitField0_;
  public static final int FOO_FIELD_NUMBER = 1;
  private volatile java.lang.Object foo_;

  /**
   * <code>optional string foo = 1;</code>
   *
   * @return Whether the foo field is set.
   */
  @java.lang.Override
  public boolean hasFoo() {
    return ((bitField0_ & 0x00000001) != 0);
  }

  /**
   * <code>optional string foo = 1;</code>
   *
   * @return The foo.
   */
  @java.lang.Override
  public java.lang.String getFoo() {
    java.lang.Object ref = foo_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    }
    else {
      com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      foo_ = s;
      return s;
    }
  }

  /**
   * <code>optional string foo = 1;</code>
   *
   * @return The bytes for foo.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
  getFooBytes() {
    java.lang.Object ref = foo_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                      (java.lang.String) ref);
      foo_ = b;
      return b;
    }
    else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BLAH_FIELD_NUMBER = 2;
  private cn.taketoday.protobuf.SecondMsg blah_;

  /**
   * <code>optional .SecondMsg blah = 2;</code>
   *
   * @return Whether the blah field is set.
   */
  @java.lang.Override
  public boolean hasBlah() {
    return ((bitField0_ & 0x00000002) != 0);
  }

  /**
   * <code>optional .SecondMsg blah = 2;</code>
   *
   * @return The blah.
   */
  @java.lang.Override
  public cn.taketoday.protobuf.SecondMsg getBlah() {
    return blah_ == null ? cn.taketoday.protobuf.SecondMsg.getDefaultInstance() : blah_;
  }

  /**
   * <code>optional .SecondMsg blah = 2;</code>
   */
  @java.lang.Override
  public cn.taketoday.protobuf.SecondMsgOrBuilder getBlahOrBuilder() {
    return blah_ == null ? cn.taketoday.protobuf.SecondMsg.getDefaultInstance() : blah_;
  }

  private byte memoizedIsInitialized = -1;

  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1)
      return true;
    if (isInitialized == 0)
      return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
          throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, foo_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(2, getBlah());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1)
      return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, foo_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
              .computeMessageSize(2, getBlah());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
      return true;
    }
    if (!(obj instanceof cn.taketoday.protobuf.Msg)) {
      return super.equals(obj);
    }
    cn.taketoday.protobuf.Msg other = (cn.taketoday.protobuf.Msg) obj;

    if (hasFoo() != other.hasFoo())
      return false;
    if (hasFoo()) {
      if (!getFoo()
              .equals(other.getFoo()))
        return false;
    }
    if (hasBlah() != other.hasBlah())
      return false;
    if (hasBlah()) {
      if (!getBlah()
              .equals(other.getBlah()))
        return false;
    }
    if (!unknownFields.equals(other.unknownFields))
      return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasFoo()) {
      hash = (37 * hash) + FOO_FIELD_NUMBER;
      hash = (53 * hash) + getFoo().hashCode();
    }
    if (hasBlah()) {
      hash = (37 * hash) + BLAH_FIELD_NUMBER;
      hash = (53 * hash) + getBlah().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static cn.taketoday.protobuf.Msg parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static cn.taketoday.protobuf.Msg parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static cn.taketoday.protobuf.Msg parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static cn.taketoday.protobuf.Msg parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static cn.taketoday.protobuf.Msg parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static cn.taketoday.protobuf.Msg parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static cn.taketoday.protobuf.Msg parseFrom(java.io.InputStream input)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
  }

  public static cn.taketoday.protobuf.Msg parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static cn.taketoday.protobuf.Msg parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
  }

  public static cn.taketoday.protobuf.Msg parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }

  public static cn.taketoday.protobuf.Msg parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
  }

  public static cn.taketoday.protobuf.Msg parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }

  public static Builder newBuilder(cn.taketoday.protobuf.Msg prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
           ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }

  /**
   * Protobuf type {@code Msg}
   */
  public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:Msg)
          cn.taketoday.protobuf.MsgOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
      return cn.taketoday.protobuf.OuterSample.internal_static_Msg_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
      return cn.taketoday.protobuf.OuterSample.internal_static_Msg_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                      cn.taketoday.protobuf.Msg.class, cn.taketoday.protobuf.Msg.Builder.class);
    }

    // Construct using cn.taketoday.protobuf.Msg.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }

    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getBlahFieldBuilder();
      }
    }

    @java.lang.Override
    public Builder clear() {
      super.clear();
      foo_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      if (blahBuilder_ == null) {
        blah_ = null;
      }
      else {
        blahBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
    getDescriptorForType() {
      return cn.taketoday.protobuf.OuterSample.internal_static_Msg_descriptor;
    }

    @java.lang.Override
    public cn.taketoday.protobuf.Msg getDefaultInstanceForType() {
      return cn.taketoday.protobuf.Msg.getDefaultInstance();
    }

    @java.lang.Override
    public cn.taketoday.protobuf.Msg build() {
      cn.taketoday.protobuf.Msg result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public cn.taketoday.protobuf.Msg buildPartial() {
      cn.taketoday.protobuf.Msg result = new cn.taketoday.protobuf.Msg(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        to_bitField0_ |= 0x00000001;
      }
      result.foo_ = foo_;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        if (blahBuilder_ == null) {
          result.blah_ = blah_;
        }
        else {
          result.blah_ = blahBuilder_.build();
        }
        to_bitField0_ |= 0x00000002;
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }

    @java.lang.Override
    public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
      return super.setField(field, value);
    }

    @java.lang.Override
    public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }

    @java.lang.Override
    public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }

    @java.lang.Override
    public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }

    @java.lang.Override
    public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof cn.taketoday.protobuf.Msg) {
        return mergeFrom((cn.taketoday.protobuf.Msg) other);
      }
      else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(cn.taketoday.protobuf.Msg other) {
      if (other == cn.taketoday.protobuf.Msg.getDefaultInstance())
        return this;
      if (other.hasFoo()) {
        bitField0_ |= 0x00000001;
        foo_ = other.foo_;
        onChanged();
      }
      if (other.hasBlah()) {
        mergeBlah(other.getBlah());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      cn.taketoday.protobuf.Msg parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      }
      catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (cn.taketoday.protobuf.Msg) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      }
      finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int bitField0_;

    private java.lang.Object foo_ = "";

    /**
     * <code>optional string foo = 1;</code>
     *
     * @return Whether the foo field is set.
     */
    public boolean hasFoo() {
      return ((bitField0_ & 0x00000001) != 0);
    }

    /**
     * <code>optional string foo = 1;</code>
     *
     * @return The foo.
     */
    public java.lang.String getFoo() {
      java.lang.Object ref = foo_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        foo_ = s;
        return s;
      }
      else {
        return (java.lang.String) ref;
      }
    }

    /**
     * <code>optional string foo = 1;</code>
     *
     * @return The bytes for foo.
     */
    public com.google.protobuf.ByteString
    getFooBytes() {
      java.lang.Object ref = foo_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
        foo_ = b;
        return b;
      }
      else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    /**
     * <code>optional string foo = 1;</code>
     *
     * @param value The foo to set.
     * @return This builder for chaining.
     */
    public Builder setFoo(
            java.lang.String value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000001;
      foo_ = value;
      onChanged();
      return this;
    }

    /**
     * <code>optional string foo = 1;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearFoo() {
      bitField0_ = (bitField0_ & ~0x00000001);
      foo_ = getDefaultInstance().getFoo();
      onChanged();
      return this;
    }

    /**
     * <code>optional string foo = 1;</code>
     *
     * @param value The bytes for foo to set.
     * @return This builder for chaining.
     */
    public Builder setFooBytes(
            com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000001;
      foo_ = value;
      onChanged();
      return this;
    }

    private cn.taketoday.protobuf.SecondMsg blah_;
    private com.google.protobuf.SingleFieldBuilderV3<
            cn.taketoday.protobuf.SecondMsg, cn.taketoday.protobuf.SecondMsg.Builder, cn.taketoday.protobuf.SecondMsgOrBuilder> blahBuilder_;

    /**
     * <code>optional .SecondMsg blah = 2;</code>
     *
     * @return Whether the blah field is set.
     */
    public boolean hasBlah() {
      return ((bitField0_ & 0x00000002) != 0);
    }

    /**
     * <code>optional .SecondMsg blah = 2;</code>
     *
     * @return The blah.
     */
    public cn.taketoday.protobuf.SecondMsg getBlah() {
      if (blahBuilder_ == null) {
        return blah_ == null ? cn.taketoday.protobuf.SecondMsg.getDefaultInstance() : blah_;
      }
      else {
        return blahBuilder_.getMessage();
      }
    }

    /**
     * <code>optional .SecondMsg blah = 2;</code>
     */
    public Builder setBlah(cn.taketoday.protobuf.SecondMsg value) {
      if (blahBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        blah_ = value;
        onChanged();
      }
      else {
        blahBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      return this;
    }

    /**
     * <code>optional .SecondMsg blah = 2;</code>
     */
    public Builder setBlah(
            cn.taketoday.protobuf.SecondMsg.Builder builderForValue) {
      if (blahBuilder_ == null) {
        blah_ = builderForValue.build();
        onChanged();
      }
      else {
        blahBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      return this;
    }

    /**
     * <code>optional .SecondMsg blah = 2;</code>
     */
    public Builder mergeBlah(cn.taketoday.protobuf.SecondMsg value) {
      if (blahBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
                blah_ != null &&
                blah_ != cn.taketoday.protobuf.SecondMsg.getDefaultInstance()) {
          blah_ =
                  cn.taketoday.protobuf.SecondMsg.newBuilder(blah_).mergeFrom(value).buildPartial();
        }
        else {
          blah_ = value;
        }
        onChanged();
      }
      else {
        blahBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000002;
      return this;
    }

    /**
     * <code>optional .SecondMsg blah = 2;</code>
     */
    public Builder clearBlah() {
      if (blahBuilder_ == null) {
        blah_ = null;
        onChanged();
      }
      else {
        blahBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    /**
     * <code>optional .SecondMsg blah = 2;</code>
     */
    public cn.taketoday.protobuf.SecondMsg.Builder getBlahBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getBlahFieldBuilder().getBuilder();
    }

    /**
     * <code>optional .SecondMsg blah = 2;</code>
     */
    public cn.taketoday.protobuf.SecondMsgOrBuilder getBlahOrBuilder() {
      if (blahBuilder_ != null) {
        return blahBuilder_.getMessageOrBuilder();
      }
      else {
        return blah_ == null ?
               cn.taketoday.protobuf.SecondMsg.getDefaultInstance() : blah_;
      }
    }

    /**
     * <code>optional .SecondMsg blah = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
            cn.taketoday.protobuf.SecondMsg, cn.taketoday.protobuf.SecondMsg.Builder, cn.taketoday.protobuf.SecondMsgOrBuilder>
    getBlahFieldBuilder() {
      if (blahBuilder_ == null) {
        blahBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                cn.taketoday.protobuf.SecondMsg, cn.taketoday.protobuf.SecondMsg.Builder, cn.taketoday.protobuf.SecondMsgOrBuilder>(
                getBlah(),
                getParentForChildren(),
                isClean());
        blah_ = null;
      }
      return blahBuilder_;
    }

    @java.lang.Override
    public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }

    // @@protoc_insertion_point(builder_scope:Msg)
  }

  // @@protoc_insertion_point(class_scope:Msg)
  private static final cn.taketoday.protobuf.Msg DEFAULT_INSTANCE;

  static {
    DEFAULT_INSTANCE = new cn.taketoday.protobuf.Msg();
  }

  public static cn.taketoday.protobuf.Msg getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Msg>
          PARSER = new com.google.protobuf.AbstractParser<Msg>() {
    @java.lang.Override
    public Msg parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return new Msg(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Msg> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Msg> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public cn.taketoday.protobuf.Msg getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

