[[dependency-injection]]
= 依赖注入

== 介绍

本程序通过手动添加或者自动扫描（）

== 通过 `PropertyValueResolver` 接口注入属性

> @Autowired 注入

[source,java]
----
public class Car {
  @Autowired("driver") Seat driverSeat;
  @Autowired("passenger") Seat passengerSeat;
  @Autowired("passenger1") @Required Seat passengerSeat1; // 找不到就抛异常
  @Autowired(value = "passenger2", required = true) Seat passengerSeat2; // 找不到就抛异常
  ...
}
----

> 支持 `Optional<T>` 注入的 Bean 如果不存在容器则返回的是 `Optional.empty()`

NOTE: 该方式注入不属于懒加载

[source,java]
----
public class Car {
  @Inject @Named("driver") Optional<Seat> driverSeat;
  @Inject @Named("passenger") Optional<Seat> passengerSeat;
  ...
}
----

=== 实现方式

详见: `cn.taketoday.context.autowire.OptionalPropertyValueResolver`

> 支持 JSR-250 `@Resource` 注解

[source,java]
----
public class Car {
  @Resource(name = "driver") Seat driverSeat;
  @Resource(name = "passenger") Seat passengerSeat;
  ...
}
----

=== 实现方式

详见: `cn.taketoday.context.autowire.JSR250ResourcePropertyValueResolver`

> 支持 JSR-330 `@Inject`,`@Named` 注解

[source,java]
----
public class Car {
  @Inject @Named("driver") Seat driverSeat;
  @Inject @Named("passenger") Seat passengerSeat;
  @Inject @Named("passenger") @Required Seat passengerSeat; // 找不到就抛异常
  ...
}
----

=== 实现方式

详见: `cn.taketoday.context.autowire.JSR330ResourcePropertyValueResolver`

== 使用 `ArgumentsResolvingStrategy` 注入参数

`StandardDependenciesBeanPostProcessor`

`ArgumentsResolvingStrategy` 这个接口用于处理构造器或方法的参数， 内置 的 解析器放在包 `cn.taketoday.context.autowire` 下.
分别支持:

. Map<String, T> 支持 name -> bean 类型
. Collection<T> 所有的同类型 Bean
. T 单个bean
. T[] Bean 数组
. ObjectProvider<T>,Supplier<T>

== 扩展注入

NOTE: 在使用 Spring 过程中发现，Spring 好像并不能更好的扩展，于是我想到我能不能实现很方便的扩展,以便支持多种注入方式

TODO

== 实现细节

全局抽象了 `InjectionPoint` 依赖注入点, 统一处理依赖

== 关闭 依赖注入

- 使用 DisableDependencyInjection 关闭当前 Bean 依赖注入
- 使用 DisableAllDependencyInjection 关闭 该配置类下的所有Bean的依赖注入，在工厂方法中手动注入

[source,java]
----
@Configuration
@DisableDependencyInjection
@DisableAllDependencyInjection
class Config {

 @Singleton
 @EnableDependencyInjection // 开启 DI
 Bean bean() {
   return new Bean();
 }

 @Singleton
 Bean bean() { // 由于 DisableAllDependencyInjection 关闭了 DI
   return new Bean();
 }

 @Autowired
 void bean(Bean bean) { // Autowired ignored
  // all DependencyResolvingStrategy disabled
 }
}
----
