/*
 * Copyright 2017 - 2026 the TODAY authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package infra.persistence.support;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

import infra.dao.DataAccessException;
import infra.jdbc.GeneratedKeysException;
import infra.jdbc.RepositoryManager;
import infra.jdbc.datasource.DriverManagerDataSource;
import infra.persistence.EntityMetadata;
import infra.persistence.EntityProperty;
import infra.persistence.PropertyUpdateStrategy;
import infra.persistence.annotation.GeneratedId;
import infra.persistence.annotation.Table;
import infra.persistence.annotation.UpdateBy;
import infra.persistence.annotation.Version;
import infra.persistence.event.BatchExecution;
import infra.persistence.event.BatchExecutionListener;
import infra.persistence.event.DeleteEventListener;
import infra.persistence.event.EntityFailureContext;
import infra.persistence.event.EntityOperationPhase;
import infra.persistence.event.PersistEventListener;
import infra.persistence.event.UpdateEventListener;
import infra.transaction.support.TransactionSynchronization;
import infra.transaction.support.TransactionSynchronizationManager;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.BDDMockito.given;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.spy;
import static org.mockito.Mockito.times;
import static org.mockito.Mockito.verify;

class BatchPersistTests {

  RepositoryManager repository;
  RecordingManager manager;

  @BeforeEach
  void setup() {
    repository = new RepositoryManager(new DriverManagerDataSource(
            "jdbc:h2:mem:" + UUID.randomUUID() + ";DB_CLOSE_DELAY=-1", "sa", ""));
    repository.createNamedQuery("create table batch_insert (id bigint generated by default as identity primary key, name varchar(64))")
            .executeUpdate();
    manager = new RecordingManager(repository);
  }

  @Test
  void selectionFailureNeverReportsPartialPropertiesForSingleOrBatchOperations() {
    var failures = new ArrayList<Throwable>();
    manager.getEntityEventRegistry().addListener(new PersistEventListener<Item>() {
      @Override
      public void onPersistFailed(Item entity, EntityFailureContext context) {
        var properties = context.getProperties();
        var exception = context.getException();
        assertThat(context.getPhase()).isEqualTo(EntityOperationPhase.PREPARATION);
        assertThat(properties).isNull();
        failures.add(exception);
      }
    });
    manager.getEntityEventRegistry().addListener(new UpdateEventListener<Item>() {
      @Override
      public void onUpdateFailed(Item entity, EntityFailureContext context) {
        var properties = context.getProperties();
        var exception = context.getException();
        assertThat(context.getPhase()).isEqualTo(EntityOperationPhase.PREPARATION);
        assertThat(properties).isNull();
        failures.add(exception);
      }
    });
    IllegalStateException failure = new IllegalStateException("selection failed");
    PropertyUpdateStrategy strategy = (entity, property) -> {
      if (property.getName().equals("name")) {
        throw failure;
      }
      return true;
    };
    Item entity = item("one");
    entity.id = 1L;
    assertThatThrownBy(() -> manager.persist(entity, strategy)).isSameAs(failure);
    assertThatThrownBy(() -> manager.persist(List.of(entity), strategy)).isSameAs(failure);
    assertThatThrownBy(() -> manager.updateById(entity, strategy)).isSameAs(failure);
    assertThatThrownBy(() -> manager.updateById(List.of(entity), strategy)).isSameAs(failure);
    assertThat(failures).containsExactly(failure, failure);
  }

  @Test
  void preCallbackFailuresReportUnavailablePropertiesOnce() {
    var failures = new ArrayList<Throwable>();
    IllegalStateException failure = new IllegalStateException("pre failed");
    manager.getEntityEventRegistry().addListener(new PersistEventListener<Item>() {
      @Override
      public PropertyUpdateStrategy onPrePersist(Item entity, EntityMetadata metadata, PropertyUpdateStrategy strategy) {
        throw failure;
      }

      @Override
      public void onPersistFailed(Item entity, EntityFailureContext context) {
        var properties = context.getProperties();
        var exception = context.getException();
        assertThat(context.getPhase()).isEqualTo(EntityOperationPhase.PRE_PROCESSING);
        assertThat(properties).isNull();
        failures.add(exception);
      }
    });
    manager.getEntityEventRegistry().addListener(new UpdateEventListener<Item>() {
      @Override
      public PropertyUpdateStrategy onPreUpdate(Item entity, EntityMetadata metadata, PropertyUpdateStrategy strategy) {
        throw failure;
      }

      @Override
      public void onUpdateFailed(Item entity, EntityFailureContext context) {
        var properties = context.getProperties();
        var exception = context.getException();
        assertThat(context.getPhase()).isEqualTo(EntityOperationPhase.PRE_PROCESSING);
        assertThat(properties).isNull();
        failures.add(exception);
      }
    });
    Item entity = item("one");
    entity.id = 1L;
    assertThatThrownBy(() -> manager.persist(entity)).isSameAs(failure);
    assertThatThrownBy(() -> manager.persist(List.of(entity))).isSameAs(failure);
    assertThatThrownBy(() -> manager.updateById(entity)).isSameAs(failure);
    assertThatThrownBy(() -> manager.updateById(List.of(entity))).isSameAs(failure);
    assertThat(failures).containsExactly(failure, failure);
  }

  @Test
  void versionFailureAndConditionalSelectionFailureReportNullProperties() {
    var failures = new ArrayList<Throwable>();
    manager.getEntityEventRegistry().addListener(new UpdateEventListener<Object>() {
      @Override
      public void onUpdateFailed(Object entity, EntityFailureContext context) {
        var properties = context.getProperties();
        var exception = context.getException();
        assertThat(context.getPhase()).isEqualTo(EntityOperationPhase.PREPARATION);
        assertThat(properties).isNull();
        failures.add(exception);
      }
    });
    VersionedItem versioned = new VersionedItem();
    versioned.id = 1L;
    assertThatThrownBy(() -> manager.updateById(versioned)).hasMessageContaining("version not set");
    assertThatThrownBy(() -> manager.updateById(List.of(versioned)))
            .isInstanceOf(IllegalArgumentException.class).hasMessageContaining("version not set");
    ConditionalItem conditional = new ConditionalItem();
    conditional.key = 1L;
    assertThatThrownBy(() -> manager.update(conditional, (entity, property) -> {
      throw new IllegalStateException("selection failed");
    })).hasMessage("selection failed");
    assertThat(failures).hasSize(2);
  }

  @Test
  void updateSqlFailureReportsImmutableSelectedProperties() {
    repository.createNamedQuery("insert into batch_insert(id,name) values(1,'old')").executeUpdate();
    var failures = new ArrayList<Throwable>();
    manager.getEntityEventRegistry().addListener(new UpdateEventListener<Item>() {
      @Override
      public void onUpdateFailed(Item entity, EntityFailureContext context) {
        var properties = context.getProperties();
        var exception = context.getException();
        assertThat(context.getPhase()).isEqualTo(EntityOperationPhase.EXECUTION);
        assertThat(properties).extracting(EntityProperty::getName).containsExactly("name");
        assertThatThrownBy(properties::clear).isInstanceOf(UnsupportedOperationException.class);
        failures.add(exception);
      }
    });
    Item entity = item("x".repeat(100));
    entity.id = 1L;
    assertThatThrownBy(() -> manager.updateById(entity)).isInstanceOf(DataAccessException.class);
    assertThatThrownBy(() -> manager.updateById(List.of(entity))).isInstanceOf(DataAccessException.class);
    assertThat(failures).hasSize(1);
  }

  @Test
  void exactBatchLimitDoesNotExecuteEmptyBatchAndAssignsKeysBeforeCallbacks() throws SQLException {
    manager.setMaxBatchRecords(2);
    var sizes = new ArrayList<Integer>();
    manager.getEntityEventRegistry().addListener(new BatchExecutionListener() {
      @Override
      public void postProcessing(BatchExecution execution, boolean implicitExecution, Throwable exception) {
        assertThat(exception).isNull();
        sizes.add(execution.getEntities().size());
        assertThat(execution.getAffectedRows()).isEqualTo(2);
      }
    });
    manager.getEntityEventRegistry().addListener(new PersistEventListener<IdentityItem>() {
      @Override
      public void onPostPersist(IdentityItem entity, EntityMetadata metadata, List<EntityProperty> properties) {
        assertThat(entity.id).isNotNull();
      }
    });
    IdentityItem first = new IdentityItem();
    first.name = "first";
    IdentityItem second = new IdentityItem();
    second.name = "second";
    assertThat(manager.persist(List.of(first, second))).isEqualTo(2);
    assertThat(first.id).isNotEqualTo(second.id);
    assertThat(sizes).containsExactly(2);
    verify(manager.statement, times(1)).executeBatch();
    assertThat(repository.createNamedQuery("select count(*) from batch_insert").fetchFirst(Integer.class)).isEqualTo(2);
  }

  @Test
  void aggregatesActualCountsAndPreservesUnknownCountAcrossFlushes() {
    manager.results = new int[] { 0, 3 };
    assertThat(manager.persist(List.of(item("one"), item("two")))).isEqualTo(3);
    manager.setMaxBatchRecords(1);
    manager.results = new int[] { Statement.SUCCESS_NO_INFO };
    assertThat(manager.persist(List.of(item("three"), item("four")))).isEqualTo(Statement.SUCCESS_NO_INFO);
  }

  @Test
  void failedCountsOnlyNotifyBatchListenerWithoutSuccessCallbacks() {
    manager.results = new int[] { 1, Statement.EXECUTE_FAILED };
    var failed = new ArrayList<Item>();
    var successful = new ArrayList<Item>();
    var batchFailures = new ArrayList<Throwable>();
    manager.getEntityEventRegistry().addListener(new BatchExecutionListener() {
      @Override
      public void postProcessing(BatchExecution execution, boolean implicitExecution, Throwable exception) {
        batchFailures.add(exception);
      }
    });
    PropertyUpdateStrategy strategy = PropertyUpdateStrategy.noneNull();
    manager.getEntityEventRegistry().addListener(new PersistEventListener<Item>() {
      @Override
      public void onPersistFailed(Item entity, EntityFailureContext context) {
        var properties = context.getProperties();
        assertThat(context.getPhase()).isEqualTo(EntityOperationPhase.EXECUTION);
        assertThat(properties).extracting(EntityProperty::getName).containsExactly("name");
        assertThatThrownBy(properties::clear).isInstanceOf(UnsupportedOperationException.class);
        failed.add(entity);
      }

      @Override
      public void onPostPersist(Item entity, EntityMetadata metadata, List<EntityProperty> properties) {
        successful.add(entity);
      }
    });
    Item first = item("one");
    Item second = item("two");
    assertThatThrownBy(() -> manager.persist(List.of(first, second), strategy)).isInstanceOf(DataAccessException.class);
    assertThat(failed).isEmpty();
    assertThat(batchFailures).singleElement().isInstanceOf(SQLException.class);
    assertThat(successful).isEmpty();
    assertThat(repository.createNamedQuery("select count(*) from batch_insert").fetchFirst(Integer.class)).isZero();
  }

  @Test
  void preProcessingFailureReachesPostProcessingAndAlwaysClearsEntities() {
    IllegalStateException failure = new IllegalStateException("pre failed");
    IllegalStateException postFailure = new IllegalStateException("post failed");
    var executions = new ArrayList<BatchExecution>();
    manager.getEntityEventRegistry().addListener(new BatchExecutionListener() {
      @Override
      public void preProcessing(BatchExecution execution, boolean implicitExecution) {
        throw failure;
      }

      @Override
      public void postProcessing(BatchExecution execution, boolean implicitExecution, Throwable exception) {
        assertThat(exception).isSameAs(failure);
        executions.add(execution);
        throw postFailure;
      }
    });
    assertThatThrownBy(() -> manager.persist(List.of(item("one")))).isSameAs(failure);
    assertThat(failure.getSuppressed()).containsExactly(postFailure);
    assertThat(executions).hasSize(1);
    assertThat(executions.get(0).getEntities()).isEmpty();
    assertThat(repository.createNamedQuery("select count(*) from batch_insert").fetchFirst(Integer.class)).isZero();
  }

  @Test
  void sqlFailureBypassesEntityFailureListenersAndRollsBack() {
    IllegalStateException callbackFailure = new IllegalStateException("failure listener failed");
    var failed = new ArrayList<Item>();
    manager.getEntityEventRegistry().addListener(new PersistEventListener<Item>() {
      @Override
      public void onPersistFailed(Item entity, EntityFailureContext context) {
        failed.add(entity);
        throw callbackFailure;
      }
    });
    Item first = item("first");
    Item second = item("x".repeat(100));
    assertThatThrownBy(() -> manager.persist(List.of(first, second)))
            .isInstanceOf(DataAccessException.class)
            .satisfies(ex -> assertThat(ex.getCause().getSuppressed()).doesNotContain(callbackFailure));
    assertThat(failed).isEmpty();
    assertThat(repository.createNamedQuery("select count(*) from batch_insert").fetchFirst(Integer.class)).isZero();
  }

  @Test
  void missingGeneratedKeysRollBackWithoutSuccessCallbacks() {
    manager.keys = mock(ResultSet.class);
    var successful = new ArrayList<IdentityItem>();
    var failures = new ArrayList<EntityFailureContext>();
    manager.getEntityEventRegistry().addListener(new PersistEventListener<IdentityItem>() {
      @Override
      public void onPersistFailed(IdentityItem entity, EntityFailureContext context) {
        failures.add(context);
      }

      @Override
      public void onPostPersist(IdentityItem entity, EntityMetadata metadata, List<EntityProperty> properties) {
        successful.add(entity);
      }
    });
    assertThatThrownBy(() -> manager.persist(List.of(new IdentityItem())))
            .isInstanceOf(GeneratedKeysException.class).hasMessageContaining("Missing generated key");
    assertThat(successful).isEmpty();
    assertThat(failures).isEmpty();
    assertThat(repository.createNamedQuery("select count(*) from batch_insert").fetchFirst(Integer.class)).isZero();
  }

  @Test
  void postCallbackFailureCarriesContextForSingleAndBatch() {
    IllegalStateException failure = new IllegalStateException("post failed");
    var failures = new ArrayList<EntityFailureContext>();
    manager.getEntityEventRegistry().addListener(new PersistEventListener<Item>() {
      @Override
      public void onPostPersist(Item entity, EntityMetadata metadata, List<EntityProperty> properties) {
        throw failure;
      }

      @Override
      public void onPersistFailed(Item entity, EntityFailureContext context) {
        failures.add(context);
      }
    });
    assertThatThrownBy(() -> manager.persist(item("single"))).isSameAs(failure);
    assertThatThrownBy(() -> manager.persist(List.of(item("batch")))).isSameAs(failure);
    assertThat(failures).hasSize(1).allSatisfy(context -> {
      assertThat(context.getPhase()).isEqualTo(EntityOperationPhase.POST_PROCESSING);
      assertThat(context.getException()).isSameAs(failure);
      assertThat(context.getProperties()).extracting(EntityProperty::getName).containsExactly("name");
    });
  }

  @Test
  void explicitUpdateIdIsRetainedWhenPostCallbackChangesEntityId() {
    repository.createNamedQuery("insert into batch_insert(id,name) values(42,'old')").executeUpdate();
    IllegalStateException failure = new IllegalStateException("post failed");
    var failures = new ArrayList<EntityFailureContext>();
    manager.getEntityEventRegistry().addListener(new UpdateEventListener<Item>() {
      @Override
      public void onPostUpdate(Item entity, EntityMetadata metadata, List<EntityProperty> properties, int count) {
        entity.id = 99L;
        throw failure;
      }

      @Override
      public void onUpdateFailed(Item entity, EntityFailureContext context) {
        failures.add(context);
      }
    });
    assertThatThrownBy(() -> manager.updateById(item("new"), 42L)).isSameAs(failure);
    assertThat(failures).singleElement().satisfies(context -> {
      assertThat(context.getId()).isEqualTo(42L);
      assertThat(context.getPhase()).isEqualTo(EntityOperationPhase.POST_PROCESSING);
    });
  }

  @Test
  void deletePreFailuresPreserveOriginalExceptionAndContinueFailureNotifications() {
    IllegalStateException failure = new IllegalStateException("pre delete failed");
    IllegalStateException secondary = new IllegalStateException("failure listener failed");
    var failures = new ArrayList<EntityFailureContext>();
    manager.getEntityEventRegistry().addListener(new DeleteEventListener<Item>() {
      @Override
      public void onPreDelete(Item entity, Object id, EntityMetadata metadata) {
        throw failure;
      }

      @Override
      public void onDeleteFailed(Item entity, EntityFailureContext context) {
        throw secondary;
      }
    });
    manager.getEntityEventRegistry().addListener(new DeleteEventListener<Item>() {
      @Override
      public void onDeleteFailed(Item entity, EntityFailureContext context) {
        failures.add(context);
      }
    });
    Item entity = item("one");
    entity.id = 42L;
    assertThatThrownBy(() -> manager.delete(Item.class, 42L)).isSameAs(failure);
    assertThatThrownBy(() -> manager.delete(entity)).isSameAs(failure);
    assertThat(failures).hasSize(2).allSatisfy(context -> {
      assertThat(context.getId()).isEqualTo(42L);
      assertThat(context.getPhase()).isEqualTo(EntityOperationPhase.PRE_PROCESSING);
      assertThat(context.getProperties()).isNull();
      assertThat(context.getException()).isSameAs(failure);
    });
    assertThat(failure.getSuppressed()).containsExactly(secondary, secondary);
    assertThat(manager.statement).isNull();
  }

  private static Item item(String name) {
    Item entity = new Item();
    entity.name = name;
    return entity;
  }

  @Test
  void preFailureStopsBatchWithoutEntityFailureNotifications() {
    var failed = new ArrayList<Item>();
    var phases = new ArrayList<EntityOperationPhase>();
    IllegalStateException failure = new IllegalStateException("pre failed");
    Item pending = item("pending");
    Item rejected = item("rejected");
    manager.getEntityEventRegistry().addListener(new PersistEventListener<Item>() {
      @Override
      public PropertyUpdateStrategy onPrePersist(Item entity, EntityMetadata metadata, PropertyUpdateStrategy strategy) {
        if (entity == rejected) {
          throw failure;
        }
        return strategy;
      }

      @Override
      public void onPersistFailed(Item entity, EntityFailureContext context) {
        assertThat(context.getException()).isSameAs(failure);
        failed.add(entity);
        phases.add(context.getPhase());
      }
    });
    assertThatThrownBy(() -> manager.persist(List.of(pending, rejected, item("unvisited")))).isSameAs(failure);
    assertThat(failed).isEmpty();
    assertThat(phases).isEmpty();
    assertThat(repository.createNamedQuery("select count(*) from batch_insert").fetchFirst(Integer.class)).isZero();
  }

  @Test
  void allPostListenersRunAndAggregateFailuresAfterSuccessfulExecution() {
    IllegalStateException firstFailure = new IllegalStateException("first");
    AssertionError secondFailure = new AssertionError("second");
    var notified = new ArrayList<Integer>();
    for (int index = 0; index < 3; index++) {
      int listenerIndex = index;
      manager.getEntityEventRegistry().addListener(new BatchExecutionListener() {
        @Override
        public void postProcessing(BatchExecution execution, boolean implicitExecution, Throwable exception) {
          assertThat(exception).isNull();
          notified.add(listenerIndex);
          if (listenerIndex == 0) {
            throw firstFailure;
          }
          if (listenerIndex == 1) {
            throw secondFailure;
          }
        }
      });
    }
    assertThatThrownBy(() -> manager.persist(List.of(item("one")))).isSameAs(firstFailure);
    assertThat(notified).containsExactly(0, 1, 2);
    assertThat(firstFailure.getSuppressed()).containsExactly(secondFailure);
    assertThat(repository.createNamedQuery("select count(*) from batch_insert").fetchFirst(Integer.class)).isZero();
  }

  @Test
  void allPostListenersReceiveOriginalExecutionFailure() {
    IllegalStateException failure = new IllegalStateException("execution pre failed");
    IllegalStateException secondary = new IllegalStateException("post failed");
    var notified = new ArrayList<Integer>();
    manager.getEntityEventRegistry().addListener(new BatchExecutionListener() {
      @Override
      public void preProcessing(BatchExecution execution, boolean implicitExecution) {
        throw failure;
      }

      @Override
      public void postProcessing(BatchExecution execution, boolean implicitExecution, Throwable exception) {
        assertThat(exception).isSameAs(failure);
        notified.add(0);
        throw secondary;
      }
    });
    manager.getEntityEventRegistry().addListener(new BatchExecutionListener() {
      @Override
      public void postProcessing(BatchExecution execution, boolean implicitExecution, Throwable exception) {
        assertThat(exception).isSameAs(failure);
        notified.add(1);
        throw failure;
      }
    });
    assertThatThrownBy(() -> manager.persist(List.of(item("one")))).isSameAs(failure);
    assertThat(notified).containsExactly(0, 1);
    assertThat(failure.getSuppressed()).containsExactly(secondary);
  }

  @Test
  void transactionCompletionReportsRollbackAfterEarlierSuccessfulBatch() {
    manager.setMaxBatchRecords(1);
    var completedBatches = new ArrayList<String>();
    var outcomes = new ArrayList<Integer>();
    manager.getEntityEventRegistry().addListener(new BatchExecutionListener() {
      @Override
      public void preProcessing(BatchExecution execution, boolean implicitExecution) {
        TransactionSynchronizationManager.registerSynchronization(new TransactionSynchronization() {
          @Override
          public void afterCompletion(int status) {
            outcomes.add(status);
          }
        });
      }

      @Override
      public void postProcessing(BatchExecution execution, boolean implicitExecution, Throwable exception) {
        if (exception == null) {
          completedBatches.add(((Item) execution.getEntities().get(0)).name);
        }
      }
    });
    assertThatThrownBy(() -> manager.persist(List.of(item("first"), item("x".repeat(100)))))
            .isInstanceOf(DataAccessException.class);
    assertThat(completedBatches).containsExactly("first");
    assertThat(outcomes).containsExactly(TransactionSynchronization.STATUS_ROLLED_BACK,
            TransactionSynchronization.STATUS_ROLLED_BACK);
    assertThat(repository.createNamedQuery("select count(*) from batch_insert").fetchFirst(Integer.class)).isZero();
  }

  @Table("batch_insert")
  static class VersionedItem {
    public Long id;
    @Version
    public Integer version;
  }

  @Table("batch_insert")
  static class ConditionalItem {
    @UpdateBy
    public Long key;
    public String name;
  }

  @Table("batch_insert")
  static class Item {
    public Long id;
    public String name;
  }

  @Table("batch_insert")
  static class IdentityItem {
    @GeneratedId
    public Long id;
    public String name;
  }

  static class RecordingManager extends DefaultEntityManager {
    int[] results;
    ResultSet keys;
    PreparedStatement statement;

    RecordingManager(RepositoryManager repository) {
      super(repository);
    }

    @Override
    protected PreparedStatement prepareStatement(Connection connection, String sql, boolean generatedKeys) throws SQLException {
      statement = spy(connection.prepareStatement(sql, generatedKeys ? Statement.RETURN_GENERATED_KEYS : Statement.NO_GENERATED_KEYS));
      if (results != null) {
        given(statement.executeBatch()).willReturn(results);
        given(statement.getGeneratedKeys()).willReturn(mock(ResultSet.class));
      }
      if (keys != null) {
        given(statement.getGeneratedKeys()).willReturn(keys);
      }
      return statement;
    }
  }
}
