/*
 * Copyright 2017 - 2026 the TODAY authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package infra.persistence.support;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

import infra.dao.DataAccessException;
import infra.jdbc.GeneratedKeysException;
import infra.jdbc.RepositoryManager;
import infra.jdbc.datasource.DriverManagerDataSource;
import infra.persistence.EntityMetadata;
import infra.persistence.EntityProperty;
import infra.persistence.PropertyUpdateStrategy;
import infra.persistence.annotation.GeneratedId;
import infra.persistence.annotation.Table;
import infra.persistence.event.BatchExecution;
import infra.persistence.event.BatchExecutionListener;
import infra.persistence.event.PersistEventListener;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.BDDMockito.given;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.spy;
import static org.mockito.Mockito.times;
import static org.mockito.Mockito.verify;

class BatchPersistTests {

  RepositoryManager repository;
  RecordingManager manager;

  @BeforeEach
  void setup() {
    repository = new RepositoryManager(new DriverManagerDataSource(
            "jdbc:h2:mem:" + UUID.randomUUID() + ";DB_CLOSE_DELAY=-1", "sa", ""));
    repository.createNamedQuery("create table batch_insert (id bigint generated by default as identity primary key, name varchar(64))")
            .executeUpdate();
    manager = new RecordingManager(repository);
  }

  @Test
  void exactBatchLimitDoesNotExecuteEmptyBatchAndAssignsKeysBeforeCallbacks() throws SQLException {
    manager.setMaxBatchRecords(2);
    var sizes = new ArrayList<Integer>();
    manager.getEntityEventRegistry().addListener(new BatchExecutionListener() {
      @Override
      public void postProcessing(BatchExecution execution, boolean implicitExecution, Throwable exception) {
        assertThat(exception).isNull();
        sizes.add(execution.getEntities().size());
        assertThat(execution.getAffectedRows()).isEqualTo(2);
      }
    });
    manager.getEntityEventRegistry().addListener(new PersistEventListener<IdentityItem>() {
      @Override
      public void onPostPersist(IdentityItem entity, EntityMetadata metadata, List<EntityProperty> properties) {
        assertThat(entity.id).isNotNull();
      }
    });
    IdentityItem first = new IdentityItem();
    first.name = "first";
    IdentityItem second = new IdentityItem();
    second.name = "second";
    assertThat(manager.persist(List.of(first, second))).isEqualTo(2);
    assertThat(first.id).isNotEqualTo(second.id);
    assertThat(sizes).containsExactly(2);
    verify(manager.statement, times(1)).executeBatch();
    assertThat(repository.createNamedQuery("select count(*) from batch_insert").fetchFirst(Integer.class)).isEqualTo(2);
  }

  @Test
  void aggregatesActualCountsAndPreservesUnknownCountAcrossFlushes() {
    manager.results = new int[] { 0, 3 };
    assertThat(manager.persist(List.of(item("one"), item("two")))).isEqualTo(3);
    manager.setMaxBatchRecords(1);
    manager.results = new int[] { Statement.SUCCESS_NO_INFO };
    assertThat(manager.persist(List.of(item("three"), item("four")))).isEqualTo(Statement.SUCCESS_NO_INFO);
  }

  @Test
  void failedCountsNotifyEntitiesWithoutSuccessCallbacks() {
    manager.results = new int[] { 1, Statement.EXECUTE_FAILED };
    var failed = new ArrayList<Item>();
    var successful = new ArrayList<Item>();
    PropertyUpdateStrategy strategy = PropertyUpdateStrategy.noneNull();
    manager.getEntityEventRegistry().addListener(new PersistEventListener<Item>() {
      @Override
      public void onPersistFailed(Item entity, EntityMetadata metadata, PropertyUpdateStrategy actual, Throwable exception) {
        assertThat(actual).isSameAs(strategy);
        failed.add(entity);
      }

      @Override
      public void onPostPersist(Item entity, EntityMetadata metadata, List<EntityProperty> properties) {
        successful.add(entity);
      }
    });
    Item first = item("one");
    Item second = item("two");
    assertThatThrownBy(() -> manager.persist(List.of(first, second), strategy)).isInstanceOf(DataAccessException.class);
    assertThat(failed).containsExactly(first, second);
    assertThat(successful).isEmpty();
    assertThat(repository.createNamedQuery("select count(*) from batch_insert").fetchFirst(Integer.class)).isZero();
  }

  @Test
  void preProcessingFailureReachesPostProcessingAndAlwaysClearsEntities() {
    IllegalStateException failure = new IllegalStateException("pre failed");
    IllegalStateException postFailure = new IllegalStateException("post failed");
    var executions = new ArrayList<BatchExecution>();
    manager.getEntityEventRegistry().addListener(new BatchExecutionListener() {
      @Override
      public void preProcessing(BatchExecution execution, boolean implicitExecution) {
        throw failure;
      }

      @Override
      public void postProcessing(BatchExecution execution, boolean implicitExecution, Throwable exception) {
        assertThat(exception).isSameAs(failure);
        executions.add(execution);
        throw postFailure;
      }
    });
    assertThatThrownBy(() -> manager.persist(List.of(item("one")))).hasCause(failure);
    assertThat(failure.getSuppressed()).containsExactly(postFailure);
    assertThat(executions).hasSize(1);
    assertThat(executions.get(0).getEntities()).isEmpty();
    assertThat(repository.createNamedQuery("select count(*) from batch_insert").fetchFirst(Integer.class)).isZero();
  }

  @Test
  void sqlFailureSurvivesFailureListenersAndRollsBack() {
    IllegalStateException callbackFailure = new IllegalStateException("failure listener failed");
    var failed = new ArrayList<Item>();
    manager.getEntityEventRegistry().addListener(new PersistEventListener<Item>() {
      @Override
      public void onPersistFailed(Item entity, EntityMetadata metadata, PropertyUpdateStrategy strategy, Throwable exception) {
        failed.add(entity);
        throw callbackFailure;
      }
    });
    Item first = item("first");
    Item second = item("x".repeat(100));
    assertThatThrownBy(() -> manager.persist(List.of(first, second)))
            .isInstanceOf(DataAccessException.class)
            .satisfies(ex -> assertThat(ex.getCause().getSuppressed()).contains(callbackFailure));
    assertThat(failed).containsExactly(first, second);
    assertThat(repository.createNamedQuery("select count(*) from batch_insert").fetchFirst(Integer.class)).isZero();
  }

  @Test
  void missingGeneratedKeysRollBackWithoutSuccessCallbacks() {
    manager.keys = mock(ResultSet.class);
    var successful = new ArrayList<IdentityItem>();
    manager.getEntityEventRegistry().addListener(new PersistEventListener<IdentityItem>() {
      @Override
      public void onPostPersist(IdentityItem entity, EntityMetadata metadata, List<EntityProperty> properties) {
        successful.add(entity);
      }
    });
    assertThatThrownBy(() -> manager.persist(List.of(new IdentityItem())))
            .isInstanceOf(GeneratedKeysException.class).hasMessageContaining("Missing generated key");
    assertThat(successful).isEmpty();
    assertThat(repository.createNamedQuery("select count(*) from batch_insert").fetchFirst(Integer.class)).isZero();
  }

  private static Item item(String name) {
    Item entity = new Item();
    entity.name = name;
    return entity;
  }

  @Table("batch_insert")
  static class Item {
    public Long id;
    public String name;
  }

  @Table("batch_insert")
  static class IdentityItem {
    @GeneratedId
    public Long id;
    public String name;
  }

  static class RecordingManager extends DefaultEntityManager {
    int[] results;
    ResultSet keys;
    PreparedStatement statement;

    RecordingManager(RepositoryManager repository) {
      super(repository);
    }

    @Override
    protected PreparedStatement prepareStatement(Connection connection, String sql, boolean generatedKeys) throws SQLException {
      statement = spy(connection.prepareStatement(sql, generatedKeys ? Statement.RETURN_GENERATED_KEYS : Statement.NO_GENERATED_KEYS));
      if (results != null) {
        given(statement.executeBatch()).willReturn(results);
        given(statement.getGeneratedKeys()).willReturn(mock(ResultSet.class));
      }
      if (keys != null) {
        given(statement.getGeneratedKeys()).willReturn(keys);
      }
      return statement;
    }
  }
}
