[[cache-annotations]]
= 基于注解的声明式缓存

对于缓存声明，Infra 的缓存抽象提供了一组 Java 注解：

* `@Cacheable`: 触发缓存填充。
* `@CacheEvict`: 触发缓存逐出。
* `@CachePut`: 在不干扰方法执行的情况下更新缓存。
* `@Caching`: 将多个缓存操作重新组合到一个方法上。
* `@CacheConfig`: 在类级别共享一些常见的缓存相关设置。

[[cache-annotations-cacheable]]
== @Cacheable 注解

顾名思义，`@Cacheable` 用于划分可缓存的方法——即，将结果存储在缓存中的方法，以便在后续调用（使用相同的参数）时，返回缓存中的值而无需实际调用该方法。
在最简单的形式中，注解声明需要与缓存的名称相关联，如下例所示：

[source,java,indent=0,subs="verbatim,quotes"]
----
@Cacheable("books")
public Book findBook(ISBN isbn) { ... }
----

在前面的代码片段中，`findBook` 方法与名为 `books` 的缓存相关联。
每次调用该方法时，都会检查缓存以查看调用是否已执行且无需重复。
虽然在大多数情况下只声明一个缓存，但注解允许指定多个名称，以便使用多个缓存。
在这种情况下，将在尝试调用该方法之前检查每个缓存——如果命中至少一个缓存，则返回相关值。

[[cache-annotations-cacheput]]
== @CachePut 注解

对于需要在不干扰方法执行的情况下更新缓存的情况，可以使用 `@CachePut` 注解。
也就是说，该方法始终被调用，其结果被放入缓存（根据 `@CachePut` 选项）。
它支持与 `@Cacheable` 相同的选项，应用于缓存填充而不是方法流优化。

[source,java,indent=0,subs="verbatim,quotes"]
----
@CachePut(cacheNames="book", key="#isbn")
public Book updateBook(ISBN isbn, BookDescriptor descriptor) { ... }
----

[[cache-annotations-cacheevict]]
== @CacheEvict 注解

缓存抽象不仅允许填充缓存存储，还允许逐出。
此过程对于从缓存中删除陈旧或未使用的数据非常有用。
与 `@Cacheable` 相反，`@CacheEvict` 划分执行缓存逐出的方法，即充当从缓存中删除数据的触发器的方法。
与其兄弟一样，`@CacheEvict` 需要指定受操作影响的一个或多个缓存。

[source,java,indent=0,subs="verbatim,quotes"]
----
@CacheEvict(cacheNames="books", allEntries=true)
public void loadBooks(InputStream batch) { ... }
----

[[cache-annotations-caching]]
== @Caching 注解

有时，需要在同一方法上指定同一类型的多个注解（例如 `@CacheEvict` 或 `@CachePut`）——例如，因为条件或键表达式在不同的缓存之间是不同的。
`@Caching` 允许在同一方法上使用多个嵌套的 `@Cacheable`、`@CachePut` 和 `@CacheEvict` 注解。

[source,java,indent=0,subs="verbatim,quotes"]
----
@Caching(evict = { @CacheEvict("primary"), @CacheEvict(cacheNames="secondary", key="#p0") })
public Book importBooks(String deposit, Date date) { ... }
----

[[cache-annotations-config]]
== @CacheConfig 注解

到目前为止，我们已经看到缓存操作提供了许多自定义选项，并且这些选项可以为每个操作设置。
但是，如果某些自定义选项适用于类的所有操作，由于有些繁琐，配置它们可能会很麻烦。
例如，为类的每个缓存操作指定要使用的缓存名称可以由单个类级别定义替换。
这是 `@CacheConfig` 发挥作用的地方。

[source,java,indent=0,subs="verbatim,quotes"]
----
@CacheConfig("books")
public class BookRepositoryImpl implements BookRepository {

    @Cacheable
    public Book findBook(ISBN isbn) { .... }
}
----
