[[cache-jsr-107]]
= JCache (JSR-107) 注解

自版本 4.1 起，Infra 的缓存抽象完全支持 JCache (JSR-107) 注解：`@CacheResult`、`@CachePut`、`@CacheRemove` 和 `@CacheRemoveAll`，以及 `@CacheDefaults`、`@CacheKey` 和 `@CacheValue`。
即使不将缓存存储迁移到 JSR-107，也可以使用这些注解。
内部实现使用 Infra 的缓存抽象，并提供符合规范的默认 `CacheResolver` 和 `KeyGenerator` 实现。
换句话说，如果你已经在使用 Infra 的缓存抽象，你可以切换到这些标准注解，而无需更改缓存存储（或配置）。

[[cache-jsr-107-summary]]
== 功能总结

下表描述了核心 JCache 注解与 Infra 抽象之间的映射：

|===
| JCache | Infra | 描述

| `@CacheResult`
| `@Cacheable`
| 方法调用被触发，结果被存储在缓存中。如果缓存中已存在值，则返回该值，不调用方法。

| `@CachePut`
| `@CachePut`
| 方法调用始终被触发，结果被存储在缓存中。

| `@CacheRemove`
| `@CacheEvict`
| 从缓存中删除条目。

| `@CacheRemoveAll`
| `@CacheEvict(allEntries=true)`
| 从缓存中删除所有条目。

| `@CacheDefaults`
| `@CacheConfig`
| 在类级别共享常见的缓存设置。
|===

[[cache-jsr-107-enabling]]
== 启用 JCache 支持

要启用 JCache 支持，你需要添加 `infra-context-support` 模块，并确保类路径中存在 `javax.cache:cache-api` 库。
然后，你可以像启用 Infra 注解一样启用 JCache 注解：

[source,java,indent=0,subs="verbatim,quotes"]
----
@Configuration
@EnableCaching
public class AppConfig {
}
----

或者在 XML 中：

[source,xml,indent=0,subs="verbatim,quotes"]
----
<cache:annotation-driven/>
----

Infra 会自动检测 JCache API 是否存在，并相应地配置必要的支持 bean。
