[[jmx-exporting]]
= 将 Bean 导出到 JMX

Infra JMX 框架的核心类是 `MBeanExporter`。
此类负责获取 Infra bean 并将其注册到 JMX `MBeanServer`。
例如，考虑以下示例：

[source,xml,indent=0,subs="verbatim,quotes"]
----
<bean id="exporter" class="infra.jmx.export.MBeanExporter">
    <property name="beans">
        <map>
            <entry key="bean:name=testBean1" value-ref="testBean"/>
        </map>
    </property>
</bean>

<bean id="testBean" class="infra.jmx.JmxTestBean">
    <property name="name" value="TEST"/>
    <property name="age" value="100"/>
</bean>
----

在这个定义中，`testBean` bean 在名为 `bean:name=testBean1` 的 `ObjectName` 下导出到 `MBeanServer`。
默认情况下，`MBeanExporter` 尝试检测正在运行的 `MBeanServer` 并向其注册 bean。
如果只有一个 MBeanServer 在运行，此行为将起作用。

[[jmx-exporting-mbeanserver]]
== MBeanServer

如果在此配置中未提供 `server` 属性，则 `MBeanExporter` 尝试查找正在运行的 `MBeanServer`。
如果只有一个 `MBeanServer` 可用，它将使用该服务器。
这在大多数情况下（例如 Tomcat 或 JBoss 等容器环境）都有效。
但是，如果你需要创建一个新的 `MBeanServer` 或显式指定一个，你可以配置 `server` 属性。

[source,xml,indent=0,subs="verbatim,quotes"]
----
<bean id="mbeanServer" class="infra.jmx.support.MBeanServerFactoryBean"/>

<bean id="exporter" class="infra.jmx.export.MBeanExporter">
    <property name="server" ref="mbeanServer"/>
    ...
</bean>
----

[[jmx-exporting-lazy]]
== 延迟初始化 MBean

如果你配置了延迟初始化的 bean，`MBeanExporter` 不会打破该契约。
它不会实例化 bean 只是为了将其注册到 JMX。
相反，它会等到 bean 被应用程序请求时才进行注册。

[[jmx-exporting-auto]]
== 自动注册 MBean

除了显式列出 bean 之外，`MBeanExporter` 还可以自动检测符合特定条件的 bean 并将其注册。
例如，你可以配置它以自动注册任何实现了 `StandardMBean` 接口的 bean。

[[jmx-exporting-annotations]]
== 基于注解的 MBean 导出

Infra 提供了注解来简化 MBean 的创建和导出。
通过使用 `@ManagedResource`、`@ManagedAttribute` 和 `@ManagedOperation`，你可以轻松地将任何 bean 转换为 MBean。

[source,java,indent=0,subs="verbatim,quotes"]
----
@ManagedResource(objectName="bean:name=testBean4", description="My Managed Bean")
public class AnnotationTestBean {

    private String name;
    private int age;

    @ManagedAttribute(description="The Age Attribute")
    public int getAge() {
        return age;
    }

    public void setAge(int age) {
        this.age = age;
    }

    @ManagedAttribute(description="The Name Attribute")
    public void setName(String name) {
        this.name = name;
    }

    @ManagedAttribute(defaultValue="NAME", currencyTimeLimit=20)
    public String getName() {
        return name;
    }

    @ManagedOperation(description="Add two numbers")
    public int add(int x, int y) {
        return x + y;
    }
}
----

要启用这些注解，你需要配置 `AnnotationMBeanExporter` 或使用 `<context:mbean-export/>`。
