[[jmx-interface]]
= 控制 MBean 接口的管理

在上一节中，我们看到 `MBeanExporter` 能够导出实现 `StandardMBean` 接口的 bean 或使用注解标记的 bean。
但是，如果你想导出没有实现特定接口且无法修改源代码的第三方 bean 怎么办？
Infra 提供了几种解决方案。

[[jmx-interface-assembler]]
== MBeanInfoAssembler 接口

在幕后，`MBeanExporter` 委托给 `org.springframework.jmx.export.assembler.MBeanInfoAssembler` 接口的实现，该接口负责定义每个 bean 上公开的管理接口。
默认实现是 `SimpleReflectiveMBeanInfoAssembler`，它只公开定义在接口中的方法（如果 bean 实现了接口）或所有公共方法（如果 bean 没有实现接口）。

[[jmx-interface-method-name]]
== MethodNameBasedMBeanInfoAssembler

`MethodNameBasedMBeanInfoAssembler` 允许你指定要作为属性和操作公开的方法名称列表。

[source,xml,indent=0,subs="verbatim,quotes"]
----
<bean id="assembler" class="infra.jmx.export.assembler.MethodNameBasedMBeanInfoAssembler">
    <property name="managedMethods">
        <value>add,myOperation,getName,setName,getAge</value>
    </property>
</bean>

<bean id="exporter" class="infra.jmx.export.MBeanExporter">
    <property name="beans">
        <map>
            <entry key="bean:name=testBean5" value-ref="testBean"/>
        </map>
    </property>
    <property name="assembler" ref="assembler"/>
</bean>
----

在这个例子中，只有 `add`、`myOperation`、`getName`、`setName` 和 `getAge` 方法会被公开。

[[jmx-interface-interface-based]]
== InterfaceBasedMBeanInfoAssembler

`InterfaceBasedMBeanInfoAssembler` 允许你指定一组接口，只有这些接口中定义的方法才会被公开。

[source,xml,indent=0,subs="verbatim,quotes"]
----
<bean id="assembler" class="infra.jmx.export.assembler.InterfaceBasedMBeanInfoAssembler">
    <property name="managedInterfaces">
        <value>infra.jmx.IJmxTestBean</value>
    </property>
</bean>
----

这对于限制管理接口的可见性非常有用，特别是当你不控制 bean 的类定义时。

[[jmx-interface-metadata]]
== MetadataMBeanInfoAssembler

`MetadataMBeanInfoAssembler` 使用元数据（如注解）来驱动管理接口的创建。
这是 `@ManagedResource` 支持背后的机制。
如果你想使用自定义注解或不同的元数据源，你可以配置此汇编器。
