[[jmx-jsr160]]
= 使用 JSR-160 连接器

对于远程访问，Infra JMX 模块在 `infra.jmx.support` 包中提供了两个 `FactoryBean` 实现，用于创建服务器端和客户端连接器。


[[jmx-jsr160-server]]
== 服务器端连接器

要让 Infra JMX 创建、启动并公开 JSR-160 `JMXConnectorServer`，可以使用以下配置：

[source,xml,indent=0,subs="verbatim,quotes"]
----
	<bean id="serverConnector" class="infra.jmx.support.ConnectorServerFactoryBean"/>
----

默认情况下，`ConnectorServerFactoryBean` 创建绑定到 `service:jmx:jmxmp://localhost:9875` 的 `JMXConnectorServer`。因此，`serverConnector` bean 通过 localhost 端口 9875 上的 JMXMP 协议向客户端公开本地 `MBeanServer`。请注意，JMXMP 协议被 JSR 160 规范标记为可选。目前，主要的开源 JMX 实现 MX4J 和 JDK 提供的实现不支持 JMXMP。

要指定另一个 URL 并将 `JMXConnectorServer` 本身注册到 `MBeanServer`，您可以分别使用 `serviceUrl` 和 `ObjectName` 属性，如下例所示：

[source,xml,indent=0,subs="verbatim,quotes"]
----
<bean id="serverConnector"
    class="infra.jmx.support.ConnectorServerFactoryBean">
  <property name="objectName" value="connector:name=rmi"/>
  <property name="serviceUrl"
      value="service:jmx:rmi://localhost/jndi/rmi://localhost:1099/myconnector"/>
</bean>
----

如果设置了 `ObjectName` 属性，Infra 会自动将您的连接器注册到该 `ObjectName` 下的 `MBeanServer`。以下示例显示了在创建 `JMXConnector` 时可以传递给 `ConnectorServerFactoryBean` 的完整参数集：

[source,xml,indent=0,subs="verbatim,quotes"]
----
<bean id="serverConnector"
    class="infra.jmx.support.ConnectorServerFactoryBean">
  <property name="objectName" value="connector:name=iiop"/>
  <property name="serviceUrl"
    value="service:jmx:iiop://localhost/jndi/iiop://localhost:900/myconnector"/>
  <property name="threaded" value="true"/>
  <property name="daemon" value="true"/>
  <property name="environment">
    <map>
      <entry key="someKey" value="someValue"/>
    </map>
  </property>
</bean>
----

请注意，当您使用基于 RMI 的连接器时，需要启动查找服务（`tnameserv` 或 `rmiregistry`）才能完成名称注册。


[[jmx-jsr160-client]]
== 客户端连接器

要创建到远程启用 JSR-160 的 `MBeanServer` 的 `MBeanServerConnection`，可以使用 `MBeanServerConnectionFactoryBean`，如下例所示：

[source,xml,indent=0,subs="verbatim,quotes"]
----
<bean id="clientConnector" class="infra.jmx.support.MBeanServerConnectionFactoryBean">
  <property name="serviceUrl" value="service:jmx:rmi://localhost/jndi/rmi://localhost:1099/jmxrmi"/>
</bean>
----


[[jmx-jsr160-protocols]]
== 基于 Hessian 或 SOAP 的 JMX

JSR-160 允许扩展客户端和服务器之间的通信方式。前面部分中显示的示例使用了 JSR-160 规范（IIOP 和 JRMP）和（可选）JMXMP 要求的强制性基于 RMI 的实现。通过使用其他提供程序或 JMX 实现（例如 http://mx4j.sourceforge.net[MX4J]），您可以利用诸如 SOAP 或 Hessian 之类的协议通过简单的 HTTP 或 SSL 等，如下例所示：

[source,xml,indent=0,subs="verbatim,quotes"]
----
<bean id="serverConnector" class="infra.jmx.support.ConnectorServerFactoryBean">
  <property name="objectName" value="connector:name=burlap"/>
  <property name="serviceUrl" value="service:jmx:burlap://localhost:9874"/>
</bean>
----

在前面的示例中，我们使用了 MX4J 3.0.0。有关更多信息，请参阅官方 MX4J 文档。
