[[jmx-jsr160]]
= JSR-160 连接器

JSR-160 规范（Java 管理扩展远程 API）定义了通过各种协议进行远程 JMX 访问的标准方式。
Infra 提供了对 JSR-160 连接器的配置支持。

[[jmx-jsr160-server]]
== 服务器端连接器

要启用远程访问，你需要配置一个 `JMXConnectorServer`。
Infra 的 `ConnectorServerFactoryBean` 使这变得简单。

[source,xml,indent=0,subs="verbatim,quotes"]
----
<bean id="serverConnector" class="infra.jmx.support.ConnectorServerFactoryBean">
    <property name="objectName" value="connector:name=rmi"/>
    <property name="serviceUrl" value="service:jmx:rmi://localhost/jndi/rmi://localhost:1099/myconnector"/>
</bean>
----

默认情况下，`ConnectorServerFactoryBean` 创建一个 `JMXConnectorServer` 并将其绑定到本地 `MBeanServer`。
`serviceUrl` 属性指定客户端用于连接的 URL。

[[jmx-jsr160-client]]
== 客户端连接器

在客户端，你需要创建一个 `JMXConnector` 来连接到远程服务器。
Infra 的 `MBeanServerConnectionFactoryBean` 提供了对此的抽象。

[source,xml,indent=0,subs="verbatim,quotes"]
----
<bean id="clientConnector" class="infra.jmx.support.MBeanServerConnectionFactoryBean">
    <property name="serviceUrl" value="service:jmx:rmi://localhost/jndi/rmi://localhost:1099/myconnector"/>
</bean>
----

这个 bean 产生一个 `MBeanServerConnection`，它可以被注入到其他 bean 中，例如 `MBeanProxyFactoryBean`。

[[jmx-jsr160-protocols]]
== 协议支持

JSR-160 支持多种协议，包括 RMI、IIOP 和 JMXMP。
RMI 是默认协议，也是最常用的。
通过更改 `serviceUrl`，你可以切换协议。

* RMI: `service:jmx:rmi://host:port/jndi/rmi://host:port/connector`
* JMXMP: `service:jmx:jmxmp://host:port`

注意，JMXMP 是一个可选协议，可能需要额外的库（`jmxremote_optional.jar`）。

[[jmx-jsr160-burlap-hessian]]
== Burlap/Hessian/SOAP JMX

除了标准的 JSR-160 连接器外，Infra 还支持通过 Burlap、Hessian 和 SOAP 公开 JMX。
这些是非标准的，但在某些防火墙受限的环境中可能很有用。
这需要配置特定的适配器。
