[[mvc-ann-responsebody]]
= `@ResponseBody`

您可以在方法上使用 `@ResponseBody` 注解，使返回内容通过 xref:integration/rest-clients.adoc#rest-message-conversion[`HttpMessageConverter`]
序列化到响应体。
以下清单显示了一个示例：

[tabs]
======
Java::
+
[source,java,indent=0,subs="verbatim,quotes",role="primary"]
----
@GetMapping("/accounts/{id}")
@ResponseBody
public Account handle() {
  // ...
}
----
======

`@ResponseBody` 也支持在类级别使用，在这种情况下，它被所有控制器方法继承。
这就是 `@RestController` 的效果，它只不过是用 `@Controller` 和 `@ResponseBody` 标记的元注解。

可以返回 `Resource` 对象作为文件内容，将提供的资源的 `InputStream` 内容复制到响应 `OutputStream`。
注意，`InputStream` 应该由 `Resource` 句柄延迟检索，以便在复制到响应后可靠地关闭它。
如果您为此目的使用 `InputStreamResource`，请确保使用按需 `InputStreamSource` 构建它
（例如，通过检索实际 `InputStream` 的 lambda 表达式）。

您可以将 `@ResponseBody` 与响应式类型一起使用。
有关更多详细信息，请参阅 xref:web/webmvc/mvc-ann-async.adoc[异步请求] 和 xref:web/webmvc/mvc-ann-async.adoc#mvc-ann-async-reactive-types[响应式类型]。

您可以使用 xref:web/webmvc/mvc-config.adoc[MVC 配置] 的 xref:web/webmvc/mvc-config/message-converters.adoc[消息转换器]
选项来配置或自定义消息转换。

您可以将 `@ResponseBody` 方法与 JSON 序列化视图结合使用。
有关详细信息，请参阅 xref:web/webmvc/mvc-controller/ann-methods/jackson.adoc[Jackson JSON]。
