/*
 * Copyright 2017 - 2024 the original author or authors.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see [https://www.gnu.org/licenses/]
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: sample.proto
// Protobuf Java Version: 4.28.2

package infra.protobuf;

public interface MsgOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Msg)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string foo = 1;</code>
   * @return Whether the foo field is set.
   */
  boolean hasFoo();
  /**
   * <code>optional string foo = 1;</code>
   * @return The foo.
   */
  String getFoo();
  /**
   * <code>optional string foo = 1;</code>
   * @return The bytes for foo.
   */
  com.google.protobuf.ByteString
      getFooBytes();

  /**
   * <code>optional .SecondMsg blah = 2;</code>
   * @return Whether the blah field is set.
   */
  boolean hasBlah();
  /**
   * <code>optional .SecondMsg blah = 2;</code>
   * @return The blah.
   */
  SecondMsg getBlah();
  /**
   * <code>optional .SecondMsg blah = 2;</code>
   */
  SecondMsgOrBuilder getBlahOrBuilder();
}
