// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sample.proto

// Protobuf Java Version: 4.26.1
package cn.taketoday.protobuf;

public interface SecondMsgOrBuilder extends
        // @@protoc_insertion_point(interface_extends:SecondMsg)
        com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 blah = 1;</code>
   *
   * @return Whether the blah field is set.
   */
  boolean hasBlah();

  /**
   * <code>optional int32 blah = 1;</code>
   *
   * @return The blah.
   */
  int getBlah();
}
