[[xsd-schemas]]
= XML 模式

本附录列出了与集成技术相关的 XML 模式。

[[xsd-schemas-cache]]
== cache 模式

`cache` 标签处理 Infra 的缓存支持。
要查找有关缓存支持的更多信息，请参阅 xref:integration/cache.adoc[缓存抽象]。

* {today-framework-schema}/cache/spring-cache.xsd[spring-cache.xsd]

[[xsd-schemas-jee]]
== jee 模式

`jee` 标签处理与 Jakarta EE (J2EE) 相关的配置问题，例如查找 JNDI 对象和定义 EJB。
要查找有关 JNDI 和 EJB 支持的更多信息，请参阅 xref:data-access/transaction/strategies.adoc[JNDI] 和 xref:integration/jmx.adoc[EJB] 章节。

* {today-framework-schema}/jee/spring-jee.xsd[spring-jee.xsd]

[[xsd-schemas-jms]]
== jms 模式

`jms` 标签处理与 JMS 相关的配置问题，例如为 JMS 监听器容器配置自定义命名空间处理。
要查找有关 JMS 支持的更多信息，请参阅 xref:integration/jmx.adoc[JMS (Java 消息服务)]。

* {today-framework-schema}/jms/spring-jms.xsd[spring-jms.xsd]

[[xsd-schemas-lang]]
== lang 模式

`lang` 标签处理由 `infra.lang` 包中的类支持的配置问题，例如动态语言支持（使用 JRuby 或 Groovy 定义 bean）和脚本支持。
要查找有关动态语言支持的更多信息，请参阅 xref:core/expressions.adoc[动态语言支持]。

* {today-framework-schema}/lang/spring-lang.xsd[spring-lang.xsd]

[[xsd-schemas-task]]
== task 模式

`task` 标签处理与任务执行和调度相关的配置问题。
要查找有关任务和调度的更多信息，请参阅 xref:integration/scheduling.adoc[任务执行和调度]。

* {today-framework-schema}/task/spring-task.xsd[spring-task.xsd]
