/*
 * Copyright 2017 - 2026 the TODAY authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package infra.persistence.support;

import org.jspecify.annotations.Nullable;

import java.util.HashMap;
import java.util.UUID;

import infra.beans.factory.BeanFactory;
import infra.beans.factory.DisposableBean;
import infra.beans.factory.config.AutowireCapableBeanFactory;
import infra.persistence.EntityMetadata;
import infra.persistence.EntityMetadata.IdGeneration;
import infra.persistence.EntityProperty;
import infra.persistence.GenerationType;
import infra.persistence.IdGenerator;
import infra.persistence.IllegalEntityException;
import infra.util.ClassUtils;
import infra.util.UuidGenerator;
import infra.util.UuidV7Generator;

/**
 * Resolves and reuses one generator per type and bean-name combination within
 * this resolver. Even prototype beans are resolved only once for each combination.
 * Only instances created on demand are owned and destroyed by this resolver;
 * existing bean instances are not destroyed here. Shared generators must be
 * thread-safe.
 * The UUID strategy defaults to UUID v7 and supports an explicitly configured
 * {@link UuidGenerator}. Auto-configuration supplies a container-provided UUID
 * generator when available.
 *
 * @author <a href="https://github.com/TAKETODAY">海子 Yang</a>
 * @since 5.0
 */
public final class IdGeneratorResolver implements DisposableBean {

  private final BeanFactory beanFactory;

  private final HashMap<IdGeneration, ResolvedGenerator> resolved = new HashMap<>();

  private UuidGenerator uuidGenerator = new UuidV7Generator();

  /**
   * Create a resolver backed by the specified bean factory.
   *
   * @param beanFactory the factory used for lookup and dependency injection
   */
  public IdGeneratorResolver(BeanFactory beanFactory) {
    this.beanFactory = beanFactory;
  }

  /**
   * Configure the generator used for the UUID strategy.
   * The supplied instance must be thread-safe and remains caller-managed.
   *
   * @param uuidGenerator the generator, or {@code null} to restore UUID v7 generation
   */
  public void setUuidGenerator(@Nullable UuidGenerator uuidGenerator) {
    this.uuidGenerator = uuidGenerator == null ? new UuidV7Generator() : uuidGenerator;
  }

  /**
   * Generate and assign an application-generated ID when the entity has no ID.
   * Existing IDs and database-generated identities are left untouched.
   *
   * @param entity the entity being inserted
   * @param metadata the entity mapping metadata
   */
  public void generateId(Object entity, EntityMetadata metadata) {
    var generation = metadata.getIdGeneration();
    EntityProperty property = metadata.getIdProperty();
    if (generation == null || property == null || metadata.isAutoGeneratedId() || property.hasValue(entity)) {
      return;
    }
    Object id;
    if (generation.strategy() == GenerationType.UUID) {
      UUID uuid = uuidGenerator.generateId();
      id = property.getType() == String.class ? uuid.toString() : uuid;
    }
    else {
      id = resolve(generation).generateId(entity, metadata, property);
    }
    if (id == null || !ClassUtils.isAssignableValue(property.getType(), id)) {
      throw new IllegalEntityException("ID generator returned an incompatible value for " + property.getName());
    }
    property.setValue(entity, id);
  }

  /**
   * Resolve by name, or by type with dependency-injected creation as fallback.
   * The first successful result is cached and reused for the same type and name,
   * irrespective of the original bean scope. Failed resolutions are not cached.
   *
   * @return the generator
   */
  IdGenerator resolve(IdGeneration generation) {
    ResolvedGenerator cached = resolved.get(generation);
    if (cached == null) {
      synchronized(this) {
        cached = resolved.get(generation);
        if (cached == null) {
          cached = resolveInternal(generation.generator(), generation.generatorName());
          resolved.put(generation, cached);
        }
      }
    }
    return cached.generator();
  }

  private ResolvedGenerator resolveInternal(Class<? extends IdGenerator> type, String name) {
    if (!name.isEmpty()) {
      return new ResolvedGenerator(beanFactory.getBean(name, type), false);
    }
    IdGenerator existing = beanFactory.getBeanProvider(type).getIfAvailable();
    if (existing != null) {
      return new ResolvedGenerator(existing, false);
    }
    if (type == IdGenerator.class) {
      throw new IllegalEntityException("An ID generator class or bean name is required");
    }
    if (!(beanFactory instanceof AutowireCapableBeanFactory factory)) {
      throw new IllegalEntityException("Creating an ID generator requires an AutowireCapableBeanFactory");
    }
    return new ResolvedGenerator(factory.createBean(type), true);
  }

  @Override
  public synchronized void destroy() {
    if (beanFactory instanceof AutowireCapableBeanFactory factory) {
      for (ResolvedGenerator generator : resolved.values()) {
        if (generator.owned()) {
          factory.destroyBean(generator.generator());
        }
      }
    }
    resolved.clear();
  }

  private record ResolvedGenerator(IdGenerator generator, boolean owned) {
  }

}
