[[appendix]]
= 附录




[[xsd-schemas]]
== XML Schemas

本附录部分列出了数据访问相关的 XML 架构，包括：

* xref:data-access/appendix.adoc#xsd-schemas-tx[`tx` 架构]
* xref:data-access/appendix.adoc#xsd-schemas-jdbc[`jdbc` 架构]



[[xsd-schemas-tx]]
=== `tx` 架构

`tx` 标签用于配置 Infra 事务综合支持中的各类 bean。
这些标签在 xref:data-access/transaction.adoc[事务管理] 章节中介绍。

TIP: 我们强烈建议你查看 Infra 发布包中的 `spring-tx.xsd` 文件。
该文件包含 Infra 事务配置的 XML Schema，并涵盖 `tx` 命名空间中各元素的信息，
包括属性默认值等。该文件带有内联文档说明，因此为遵循 DRY（Don’t Repeat Yourself）
原则，这里不再重复。

为完整起见，要使用 `tx` 架构中的元素，需要在 Infra XML 配置文件顶部加入如下前置声明。
下方片段引用了正确的 schema，从而使 `tx` 命名空间中的标签可用：

[source,xml,indent=0,subs="verbatim,quotes"]
----
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns:tx="http://www.springframework.org/schema/tx" <1>
  xmlns:aop="http://www.springframework.org/schema/aop"
  xsi:schemaLocation="
    http://www.springframework.org/schema/beans
    https://www.springframework.org/schema/beans/spring-beans.xsd
    http://www.springframework.org/schema/tx
    https://www.springframework.org/schema/tx/spring-tx.xsd <2>
    http://www.springframework.org/schema/aop
    https://www.springframework.org/schema/aop/spring-aop.xsd">

  <!-- bean definitions here -->

</beans>
----
<1> 声明使用 `tx` 命名空间。
<2> 指定该位置（以及其他 schema 位置）。

NOTE: 通常在使用 `tx` 命名空间元素时，也会使用 `aop` 命名空间元素
（因为 Infra 的声明式事务支持基于 AOP 实现）。上面的 XML 片段包含了引用 `aop`
schema 所需的行，从而使 `aop` 命名空间中的元素可用。



[[xsd-schemas-jdbc]]
=== `jdbc` 架构

`jdbc` 元素可用于快速配置嵌入式数据库或初始化现有数据源。
这些元素分别在 xref:data-access/jdbc/embedded-database-support.adoc[嵌入式数据库支持]
与 xref:data-access/jdbc/initializing-datasource.adoc[初始化数据源] 中进行说明。

要使用 `jdbc` 架构中的元素，需要在 Infra XML 配置文件顶部加入如下前置声明。
下方片段引用了正确的 schema，从而使 `jdbc` 命名空间中的元素可用：

[source,xml,indent=0,subs="verbatim,quotes"]
----
	<?xml version="1.0" encoding="UTF-8"?>
	<beans xmlns="http://www.springframework.org/schema/beans"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xmlns:jdbc="http://www.springframework.org/schema/jdbc" <1>
		xsi:schemaLocation="
			http://www.springframework.org/schema/beans
			https://www.springframework.org/schema/beans/spring-beans.xsd
			http://www.springframework.org/schema/jdbc
			https://www.springframework.org/schema/jdbc/spring-jdbc.xsd"> <2>

		<!-- bean definitions here -->

	</beans>
----
<1> 声明使用 `jdbc` 命名空间。
<2> 指定该位置（以及其他 schema 位置）。
