[[appendix]]
= 附录




[[xsd-schemas]]
== XML 模式

本部分附录列出了用于数据访问的 XML 模式，包括：

* xref:data-access/appendix.adoc#xsd-schemas-tx[`tx` 模式]
* xref:data-access/appendix.adoc#xsd-schemas-jdbc[`jdbc` 模式]



[[xsd-schemas-tx]]
=== `tx` 模式

`tx` 标签用于在 Infra 对事务的全面支持中配置所有那些 bean。
这些标签在名为 xref:data-access/transaction.adoc[事务管理] 的章节中有所介绍。

TIP: 我们强烈建议您查看 Infra 发行版中随附的 `'spring-tx.xsd'` 文件。
此文件包含 Infra 事务配置的 XML 模式，并涵盖了 `tx` 命名空间中的所有各种元素，
包括属性默认值和类似信息。此文件在内部有文档说明，因此，为了遵守 DRY（不要重复自己）原则，
此处不再重复这些信息。

为了完整起见，要使用 `tx` 模式中的元素，您需要在 Infra XML 配置文件的顶部包含以下序言。
以下代码段中的文本引用了正确的模式，以便 `tx` 命名空间中的标签可供您使用：

[source,xml,indent=0,subs="verbatim,quotes"]
----
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns:tx="http://www.springframework.org/schema/tx" <1>
  xmlns:aop="http://www.springframework.org/schema/aop"
  xsi:schemaLocation="
    http://www.springframework.org/schema/beans
    https://www.springframework.org/schema/beans/spring-beans.xsd
    http://www.springframework.org/schema/tx
    https://www.springframework.org/schema/tx/spring-tx.xsd <2>
    http://www.springframework.org/schema/aop
    https://www.springframework.org/schema/aop/spring-aop.xsd">

  <!-- bean definitions here -->

</beans>
----
<1> 声明 `tx` 命名空间的使用。
<2> 指定位置（与其他模式位置一起）。

NOTE: 通常，当您使用 `tx` 命名空间中的元素时，您也在使用 `aop` 命名空间中的元素
（因为 Infra 中的声明式事务支持是通过使用 AOP 实现的）。
前面的 XML 代码段包含了引用 `aop` 模式所需的相关行，以便 `aop` 命名空间中的元素可供您使用。



[[xsd-schemas-jdbc]]
=== `jdbc` 模式

`jdbc` 元素让您可以快速配置嵌入式数据库或初始化现有的数据源。
这些元素分别记录在 xref:data-access/jdbc/embedded-database-support.adoc[嵌入式数据库支持]
和 xref:data-access/jdbc/initializing-datasource.adoc[初始化数据源] 中。

要使用 `jdbc` 模式中的元素，您需要在 Infra XML 配置文件的顶部包含以下序言。
以下代码段中的文本引用了正确的模式，以便 `jdbc` 命名空间中的元素可供您使用：

[source,xml,indent=0,subs="verbatim,quotes"]
----
	<?xml version="1.0" encoding="UTF-8"?>
	<beans xmlns="http://www.springframework.org/schema/beans"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xmlns:jdbc="http://www.springframework.org/schema/jdbc" <1>
		xsi:schemaLocation="
			http://www.springframework.org/schema/beans
			https://www.springframework.org/schema/beans/spring-beans.xsd
			http://www.springframework.org/schema/jdbc
			https://www.springframework.org/schema/jdbc/spring-jdbc.xsd"> <2>

		<!-- bean definitions here -->

	</beans>
----
<1> 声明 `jdbc` 命名空间的使用。
<2> 指定位置（与其他模式位置一起）。
