[[mvc-view-freemarker]]
= FreeMarker

https://freemarker.apache.org/[Apache FreeMarker] 是一个模板引擎，用于生成从 HTML 到电子邮件等各种文本输出。TODAY Framework 内置了 Web MVC 与 FreeMarker 模板的集成。


[[mvc-view-freemarker-contextconfig]]
== 视图配置

以下示例展示了如何将 FreeMarker 配置为视图技术：

[tabs]
======
Java::
+
[source,java,indent=0,subs="verbatim,quotes",role="primary"]
----
@Configuration
@EnableWebMvc
public class WebConfig implements WebMvcConfigurer {

  @Override
  public void configureViewResolvers(ViewResolverRegistry registry) {
    registry.freeMarker();
  }

  // 配置 FreeMarker...

  @Bean
  public FreeMarkerConfigurer freeMarkerConfigurer() {
    FreeMarkerConfigurer configurer = new FreeMarkerConfigurer();
    configurer.setTemplateLoaderPath("/WEB-INF/freemarker");
    return configurer;
  }
}
----

======


或者，您也可以声明 `FreeMarkerConfigurer` bean 以完全控制所有属性，如下例所示：

[source,xml,indent=0,subs="verbatim,quotes"]
----
<bean id="freemarkerConfig" class="infra.web.view.freemarker.FreeMarkerConfigurer">
  <property name="templateLoaderPath" value="/WEB-INF/freemarker/"/>
</bean>
----

您的模板需要存储在前面示例中 `FreeMarkerConfigurer` 指定的目录中。鉴于上述配置，如果您的控制器返回视图名称 `welcome`，解析器将查找 `/WEB-INF/freemarker/welcome.ftl` 模板。


[[mvc-views-freemarker]]
== FreeMarker 配置

您可以通过在 `FreeMarkerConfigurer` bean 上设置相应的 bean 属性，将 FreeMarker 的 'Settings' 和 'SharedVariables' 直接传递给 FreeMarker `Configuration` 对象（由 Infra 管理）。`freemarkerSettings` 属性需要一个 `java.util.Properties` 对象，而 `freemarkerVariables` 属性需要一个 `java.util.Map`。以下示例展示了如何使用 `FreeMarkerConfigurer`：

[source,xml,indent=0,subs="verbatim,quotes"]
----
<bean id="freemarkerConfig" class="infra.web.mockApi.view.freemarker.FreeMarkerConfigurer">
  <property name="templateLoaderPath" value="/WEB-INF/freemarker/"/>
  <property name="freemarkerVariables">
    <map>
      <entry key="xml_escape" value-ref="fmXmlEscape"/>
    </map>
  </property>
</bean>

<bean id="fmXmlEscape" class="freemarker.template.utility.XmlEscape"/>
----

有关适用于 `Configuration` 对象的设置和变量的详细信息，请参阅 FreeMarker 文档。


[[mvc-view-freemarker-forms]]
== 表单处理

Infra 提供了一个用于 JSP 的标签库，其中包含 `<spring:bind/>` 元素等。该元素主要让表单显示来自表单支持对象的值，并显示来自 Web 或业务层的 `Validator` 的验证失败结果。Infra 在 FreeMarker 中也支持相同的功能，并提供了用于生成表单输入元素本身的额外便捷宏。


[[mvc-view-bind-macros]]
=== 绑定宏

`infra-web.jar` 文件中为 FreeMarker 维护了一套标准宏，因此只要配置得当，应用程序始终可以使用这些宏。

Infra 模板库中定义的某些宏被视为内部（私有）宏，但宏定义中不存在此类作用域，使得所有宏对调用代码和用户模板均可见。以下部分仅集中介绍您需要在模板中直接调用的宏。如果您希望直接查看宏代码，该文件名为 `infra.ftl`，位于 `infra.web.mockApi.view.freemarker` 包中。


[[mvc-view-simple-binding]]
=== 简单绑定

在充当 Web MVC 控制器表单视图的基于 FreeMarker 模板的 HTML 表单中，您可以使用类似于下一个示例的代码来绑定字段值，并以与 JSP 等效项类似的方式显示每个输入字段的错误消息。以下示例显示了 `personForm` 视图：

[source,xml,indent=0,subs="verbatim,quotes"]
----
<!-- FreeMarker 宏必须导入到命名空间中。
  我们强烈建议坚持使用 'spring'。 -->
<#import "/spring.ftl" as spring/>
<html>
  ...
  <form action="" method="POST">
    Name:
    <@spring.bind "personForm.name"/>
    <input type="text"
      name="${spring.status.expression}"
      value="${spring.status.value?html}"/><br />
    <#list spring.status.errorMessages as error> <b>${error}</b> <br /> </#list>
    <br />
    ...
    <input type="submit" value="submit"/>
  </form>
  ...
</html>
----

`<@spring.bind>` 需要一个 'path' 参数，该参数由您的命令对象的名称（它是 'command'，除非您在控制器配置中更改了它）后跟一个点和您希望绑定到的命令对象上的字段名称组成。您还可以使用嵌套字段，例如 `command.address.street`。`bind` 宏假定默认的 HTML 转义行为由 `web.xml` 中的 `MockContextImpl` 参数 `defaultHtmlEscape` 指定。

名为 `<@spring.bindEscaped>` 的宏的另一种形式接受第二个参数，该参数显式指定是否应在状态错误消息或值中使用 HTML 转义。您可以根据需要将其设置为 `true` 或 `false`。其他表单处理宏简化了 HTML 转义的使用，您应该尽可能使用这些宏。下一节将解释它们。


[[mvc-views-form-macros]]
=== 输入宏

FreeMarker 的其他便捷宏简化了绑定和表单生成（包括验证错误显示）。永远不需要使用这些宏来生成表单输入字段，您可以将它们与简单的 HTML 或对我们之前强调的 Infra 绑定宏的直接调用混合搭配使用。

下表列出了可用的宏，显示了 FreeMarker 模板 (FTL) 定义以及每个宏采用的参数列表：

[[views-macros-defs-tbl]]
.宏定义表
[cols="3,1"]
|===
| 宏 | FTL 定义

| `message` (根据代码参数输出资源包中的字符串)
| <@spring.message code/>

| `messageText` (根据代码参数输出资源包中的字符串，
  如果失败则回退到默认参数的值)
| <@spring.messageText code, text/>

| `url` (为相对 URL 添加应用程序上下文根前缀)
| <@spring.url relativeUrl/>

| `formInput` (用于收集用户输入的标准输入字段)
| <@spring.formInput path, attributes, fieldType/>

| `formHiddenInput` (用于提交非用户输入的隐藏输入字段)
| <@spring.formHiddenInput path, attributes/>

| `formPasswordInput` (用于收集密码的标准输入字段。注意，此类型的字段中永远不会填充任何值。)
| <@spring.formPasswordInput path, attributes/>

| `formTextarea` (用于收集长自由格式文本输入的大文本字段)
| <@spring.formTextarea path, attributes/>

| `formSingleSelect` (下拉框选项，允许选择单个必需值)
| <@spring.formSingleSelect path, options, attributes/>

| `formMultiSelect` (列表框选项，允许用户选择 0 个或多个值)
| <@spring.formMultiSelect path, options, attributes/>

| `formRadioButtons` (单选按钮集，允许从可用选项中选择一个)
| <@spring.formRadioButtons path, options, separator, attributes/>

| `formCheckboxes` (复选框集，允许从可用选项中选择 0 个或多个)
| <@spring.formCheckboxes path, options, separator, attributes/>

| `formCheckbox` (单个复选框)
| <@spring.formCheckbox path, attributes/>

| `showErrors` (显示特定字段的验证错误)
| <@spring.showErrors separator, classOrStyle/>
|===

上述任何宏中的参数都具有一致的含义：

* `path`: 要绑定的字段的名称（即 "command.name"）
* `options`: 用于在输入字段中生成选项的所有可用值的 Map。映射的键表示将发布回表单对象的值，映射的值是显示在表单上的标签。通常，这样的 Map 由控制器作为参考数据提供。您还可以使用任何允许适配器实现根据需要获取 Map 条目键和值的对象（例如，`java.util.Collection`）。
* `separator`: 用作多个选项之间分隔符的序列（例如 `<br>`）。
* `attributes`: 要包含在 HTML 标签本身中的任意标签或文本的附加字符串。该字符串按字面意义由宏回显。例如，在 `textarea` 字段中，您可以提供属性（如 'rows="5" cols="60"'），或者您可以传递样式信息（如 'style="border:1px solid silver"'）。
* `classOrStyle`: 对于 `showErrors` 宏，包装每个错误的 `span` 元素使用的 CSS 类的名称。如果没有提供任何信息（或者该值为空），则错误将包装在 `<b></b>` 标签中。

以下部分概述了宏的示例。

[[mvc-views-form-macros-input]]
==== 输入字段

输入宏 `<@spring.formInput>` 使用值 `text` 作为 HTML `input` 标签的 `type` 属性。大多数浏览器将文本输入字段识别为文本输入，而不要求显式指定此 `type`。如果您想将特定类型作为 `type` 属性，请使用宏 `<@spring.formInput>` 并将所需的类型作为第三个参数传递（例如 `email` 或 `date`）。或者，使用 `<@spring.formHiddenInput>` 或 `<@spring.formPasswordInput>` 宏来更改输入类型，具体取决于您的要求。

[source,xml,indent=0,subs="verbatim,quotes"]
----
<@spring.formInput "command.name" />
<@spring.formInput "command.email" "" "email"/>
----

[[mvc-views-form-macros-textarea]]
==== 文本区域

`<@spring.formTextarea>` 宏用于生成 HTML `textarea` 元素。

[source,xml,indent=0,subs="verbatim,quotes"]
----
<@spring.formTextarea "command.notes" "rows='5' cols='80'" />
----

[[mvc-views-form-macros-select]]
==== 选择字段

可以使用 `<@spring.formSingleSelect>` 和 `<@spring.formMultiSelect>` 宏生成 HTML `select` 元素。

[source,xml,indent=0,subs="verbatim,quotes"]
----
<@spring.formSingleSelect "command.city" cityMap />
<@spring.formMultiSelect "command.skills" skillsMap />
----

[[mvc-views-form-macros-radio-check]]
==== 单选按钮和复选框

单选按钮和复选框通常以列表形式呈现，但如果您希望生成单个复选框，请使用 `<@spring.formCheckbox>` 宏。

[source,xml,indent=0,subs="verbatim,quotes"]
----
<@spring.formRadioButtons "command.gender" genderMap "" />
<@spring.formCheckboxes "command.hobbies" hobbiesMap "<br>" />
<@spring.formCheckbox "command.newsletter" />
----

[[mvc-view-freemarker-html-escaping]]
=== HTML 转义

使用上面描述的表单宏的默认用法会导致符合 HTML 4.01 的 HTML 标签，并使用 `web.xml` 中定义的 HTML 转义的默认值（由 Infra 的绑定支持使用）。为了使标签符合 XHTML 或覆盖默认的 HTML 转义值，您可以在模板中指定两个变量（或者在模型中，使它们对模板可见）。在模板中指定它们的优点是可以在模板处理稍后更改为不同的值，从而为表单中的不同字段提供不同的行为。

要切换到符合 XHTML 的标签，请为名为 `xhtmlCompliant` 的变量指定值 `true`，如下例所示：

[source,xml,indent=0,subs="verbatim,quotes"]
----
<#assign xhtmlCompliant = true>
----

在处理此指令后，Infra 宏生成的所有标签现在都符合 XHTML。

以类似的方式，您可以为每个字段指定 HTML 转义，如下例所示：

[source,xml,indent=0,subs="verbatim,quotes"]
----
<#assign htmlEscape = true>
----
