[[reacting-to-other-plugins]]
= Reacting to Other Plugins
When another plugin is applied the Infra plugin reacts by making various changes to the project's configuration.
This section describes those changes.



[[reacting-to-other-plugins.java]]
== Reacting to the Java Plugin
When Gradle's {java-plugin}[`java` plugin] is applied to a project, the Infra plugin:

1. Creates a {infra-jar-javadoc}[`InfraJar`] task named `infraJar` that will create an executable, fat jar for the project.
   The jar will contain everything on the runtime classpath of the main source set; classes are packaged in `APP-INF/classes` and jars are packaged in `APP-INF/lib`
2. Configures the `assemble` task to depend on the `infraJar` task.
3. Configures the `jar` task to use `plain` as the convention for its archive classifier.
4. Creates a {infra-build-image-javadoc}[`InfraBuildImage`] task named `infraBuildImage` that will create a OCI image using a https://buildpacks.io[buildpack].
5. Creates a {infra-run-javadoc}[`InfraRun`] task named `infraRun` that can be used to run your application using the `main` source set to find its main method and provide its runtime classpath.
6. Creates a {infra-run-javadoc}['InfraRun`] task named `infraTestRun` that can be used to run your application using the `test` source set to find its main method and provide its runtime classpath.
7. Creates a configuration named `infraArchives` that contains the artifact produced by the `infraJar` task.
8. Creates a configuration named `developmentOnly` for dependencies that are only required at development time, such as Infra's Devtools, and should not be packaged in executable jars and wars.
9. Creates a configuration named `productionRuntimeClasspath`. It is equivalent to `runtimeClasspath` minus any dependencies that only appear in the `developmentOnly` configuration.
10. Configures any `JavaCompile` tasks with no configured encoding to use `UTF-8`.
11. Configures any `JavaCompile` tasks to use the `-parameters` compiler argument.



[[reacting-to-other-plugins.kotlin]]
== Reacting to the Kotlin Plugin
When {kotlin-plugin}[Kotlin's Gradle plugin] is applied to a project, the Infra plugin:

1. Aligns the Kotlin version used in Infra's dependency management with the version of the plugin.
   This is achieved by setting the `kotlin.version` property with a value that matches the version of the Kotlin plugin.
2. Configures any `KotlinCompile` tasks to use the `-java-parameters` compiler argument.



[[reacting-to-other-plugins.war]]
== Reacting to the War Plugin
When Gradle's {war-plugin}[`war` plugin] is applied to a project, the Infra plugin:

1. Creates a {infra-war-javadoc}[`InfraWar`] task named `infraWar` that will create an executable, fat war for the project.
   In addition to the standard packaging, everything in the `providedRuntime` configuration will be packaged in `WEB-INF/lib-provided`.
2. Configures the `assemble` task to depend on the `infraWar` task.
3. Configures the `war` task to use `plain` as the convention for its archive classifier.
4. Configures the `infraArchives` configuration to contain the artifact produced by the `infraWar` task.



[[reacting-to-other-plugins.dependency-management]]
== Reacting to the Dependency Management Plugin
When the {dependency-management-plugin}[`io.spring.dependency-management` plugin] is applied to a project, the Infra plugin will automatically import the `infra-dependencies` bom.



[[reacting-to-other-plugins.application]]
== Reacting to the Application Plugin
When Gradle's {application-plugin}[`application` plugin] is applied to a project, the Infra plugin:

1. Creates a `CreateStartScripts` task named `infraStartScripts` that will create scripts that launch the artifact in the `infraArchives` configuration using `java -jar`.
   The task is configured to use the `applicationDefaultJvmArgs` property as a convention for its `defaultJvmOpts` property.
2. Creates a new distribution named `infra` and configures it to contain the artifact in the `infraArchives` configuration in its `lib` directory and the start scripts in its `bin` directory.
3. Configures the `infraRun` task to use the `mainClassName` property as a convention for its `main` property.
4. Configures the `infraRun` and `infraTestRun` tasks to use the `applicationDefaultJvmArgs` property as a convention for their `jvmArgs` property.
5. Configures the `infraJar` task to use the `mainClassName` property as a convention for the `Start-Class` entry in its manifest.
6. Configures the `infraWar` task to use the `mainClassName` property as a convention for the `Start-Class` entry in its manifest.



[[reacting-to-other-plugins.nbt]]
== Reacting to the GraalVM Native Image Plugin
When the {nbt-gradle-plugin}[GraalVM Native Image plugin] is applied to a project, the Infra plugin:

. Applies the `cn.taketoday.application.aot` plugin that:
.. Registers `aot` and `aotTest` source sets.
.. Registers a `ProcessAot` task named `processAot` that will generate AOT-optimized source for the application in the `aot` source set.
.. Configures the Java compilation and process resources tasks for the `aot` source set to depend upon `processAot`.
.. Registers a `ProcessTestAot` task named `processTestAot` that will generated AOT-optimized source for the application's tests in the `aotTest` source set.
.. Configures the Java compilation and process resources tasks for the `aotTest` source set to depend upon `processTestAot`.
. Adds the output of the `aot` source set to the classpath of the `main` GraalVM native binary.
. Adds the output of the `aotTest` source set to the classpath of the `test` GraalVM native binary.
. Configures the GraalVM extension to disable Toolchain detection.
. Configures each GraalVM native binary to require GraalVM 22.3 or later.
. Configures the `infraJar` task to include the reachability metadata produced by the `collectReachabilityMetadata` task in its jar.
. Configures the `infraBuildImage` task to use `paketobuildpacks/builder:tiny` as its builder and to set `BP_NATIVE_IMAGE` to `true` in its environment.


