/*
 * Copyright 2017 - 2026 the TODAY authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package infra.persistence;

import org.jspecify.annotations.Nullable;

import java.lang.annotation.Annotation;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Objects;

import infra.beans.BeanMetadata;
import infra.core.annotation.MergedAnnotation;
import infra.core.annotation.MergedAnnotations;
import infra.core.style.ToStringBuilder;
import infra.lang.Unmodifiable;
import infra.persistence.annotation.GeneratedId;
import infra.util.StringUtils;

/**
 * Describes the mapping between an entity class and its database representation.
 *
 * <p>It exposes the table name, the ID and version properties, the mapped entity
 * properties together with their column names, and whether the ID is auto-generated.
 * It also gives access to the merged annotations declared on the entity class.
 *
 * <p>The ID property has two views: {@link #getIdProperty()} returns only the ID
 * declared by this entity, whereas {@link #findIdProperty()} returns the effective ID
 * used by ID-based operations. For an
 * {@link infra.persistence.annotation.EntityRef @EntityRef} entity the latter may
 * resolve to the ID of the referenced entity — see {@link RefEntityMetadata}.
 *
 * <p>Instances are created by an {@link EntityMetadataFactory}, are read-only after
 * construction, and should not be instantiated by application code. The property
 * lookup map and the merged annotations are cached for efficient reuse.
 *
 * @author <a href="https://github.com/TAKETODAY">Harry Yang</a>
 * @see EntityProperty
 * @see RefEntityMetadata
 * @see EntityMetadataFactory
 * @since 4.0 2022/8/16 22:43
 */
public class EntityMetadata {

  /** The entity class this metadata was created for. */
  private final Class<?> entityClass;

  /** The bean metadata describing the entity class. */
  private final BeanMetadata beanMetadata;

  /** The name of the database table backing the entity. */
  private final String tableName;

  /** Column names of {@link #entityProperties}, including the ID column. */
  private final String[] columnNames;

  /** Column names of {@link #entityPropertiesExcludeId}, excluding the ID column. */
  private final String[] columnNamesExcludeId;

  /** All mapped entity properties, including the ID property. */
  private final EntityProperty[] entityProperties;

  /** Entity properties excluding the ID property. */
  private final EntityProperty[] entityPropertiesExcludeId;

  /** Whether the ID value is generated by the database. */
  private final boolean autoGeneratedId;

  /** Entity properties indexed by bean property name, backing {@link #findProperty(String)}. */
  private final HashMap<String, EntityProperty> propertyMap;

  /** The optimistic-locking version property, or {@code null} if none. */
  private final @Nullable EntityProperty versionProperty;

  /** The ID property declared by this entity, or {@code null} if it declares none. */
  private final @Nullable EntityProperty idProperty;

  /** Cached merged annotations of the entity class, resolved lazily. */
  private @Nullable MergedAnnotations annotations;

  protected EntityMetadata(BeanMetadata beanMetadata, Class<?> entityClass, String tableName,
          @Nullable EntityProperty idProperty, @Nullable EntityProperty versionProperty,
          List<String> columnNames, List<EntityProperty> entityProperties) {
    this.beanMetadata = beanMetadata;
    this.tableName = tableName;
    this.idProperty = idProperty;
    this.versionProperty = versionProperty;
    this.entityClass = entityClass;
    this.propertyMap = mapProperties(entityProperties);
    this.columnNames = StringUtils.toStringArray(columnNames);
    this.entityProperties = entityProperties.toArray(new EntityProperty[0]);

    if (idProperty != null) {
      entityProperties.remove(idProperty);
      columnNames.remove(idProperty.getColumnName());
    }

    this.autoGeneratedId = determineGeneratedId(idProperty);
    this.columnNamesExcludeId = StringUtils.toStringArray(columnNames);
    this.entityPropertiesExcludeId = entityProperties.toArray(new EntityProperty[0]);
  }

  private HashMap<String, EntityProperty> mapProperties(List<EntityProperty> entityProperties) {
    HashMap<String, EntityProperty> propertyMap = new HashMap<>();
    for (EntityProperty property : entityProperties) {
      propertyMap.put(property.getName(), property);
    }
    return propertyMap;
  }

  private boolean determineGeneratedId(@Nullable EntityProperty idProperty) {
    if (idProperty != null) {
      return idProperty.isPresent(GeneratedId.class);
    }
    return false;
  }

  /**
   * Return the name of the database table backing the entity.
   *
   * @return the table name
   */
  public String getTableName() {
    return tableName;
  }

  /**
   * Return the bean metadata describing the entity class.
   *
   * @return the bean metadata
   */
  public BeanMetadata getBeanMetadata() {
    return beanMetadata;
  }

  /**
   * Return the entity class this metadata was created for.
   *
   * @return the entity class
   */
  public Class<?> getEntityClass() {
    return entityClass;
  }

  /**
   * Return the column name of the ID property.
   *
   * @return the ID column name, or {@code null} if the entity has no ID
   */
  public @Nullable String getIdColumnName() {
    EntityProperty idProperty = findIdProperty();
    return idProperty != null ? idProperty.getColumnName() : null;
  }

  /**
   * Return the ID property declared by this entity itself.
   *
   * <p>This exposes only the ID bound to this entity's own class. An entity that
   * does not declare an ID of its own returns {@code null} — notably an
   * {@link infra.persistence.annotation.EntityRef @EntityRef} entity whose primary key
   * is inherited from the referenced entity. For the ID actually used by ID-based
   * operations, which may fall back to the referenced entity, use
   * {@link #findIdProperty()} instead.
   *
   * @return the ID property declared by this entity, or {@code null} if it declares none
   * @see #findIdProperty()
   */
  public @Nullable EntityProperty getIdProperty() {
    return idProperty;
  }

  /**
   * Return the optimistic-locking version property.
   *
   * @return the version property, or {@code null} if none is declared
   */
  public @Nullable EntityProperty getVersionProperty() {
    return versionProperty;
  }

  /**
   * Return the column names of the mapped properties.
   *
   * <p>When {@code excludeId} is {@code false}, the ID column (if the entity has one)
   * is included; when {@code true}, it is omitted. The result mirrors
   * {@link #getEntityProperties(boolean)} called with the same argument, so that a
   * column name and its property share the same position.
   *
   * <p>The returned array is the internally cached instance; callers must not modify
   * it.
   *
   * @param excludeId whether to omit the ID column from the result
   * @return the column names, never {@code null}
   */
  @Unmodifiable
  public String[] getColumnNames(boolean excludeId) {
    return excludeId ? columnNamesExcludeId : columnNames;
  }

  /**
   * Return the mapped entity properties.
   *
   * <p>When {@code excludeId} is {@code false}, the ID property (if the entity has
   * one) is included; when {@code true}, it is omitted. The result mirrors
   * {@link #getColumnNames(boolean)} called with the same argument.
   *
   * <p>The returned array is the internally cached instance; callers must not modify
   * it.
   *
   * @param excludeId whether to omit the ID property from the result
   * @return the entity properties, never {@code null}
   */
  @Unmodifiable
  public EntityProperty[] getEntityProperties(boolean excludeId) {
    return excludeId ? entityPropertiesExcludeId : entityProperties;
  }

  /**
   * Return whether the ID value is generated by the database.
   *
   * @return {@code true} if the ID is auto-generated, {@code false} otherwise
   */
  public boolean isAutoGeneratedId() {
    return autoGeneratedId;
  }

  /**
   * Return the effective ID property used for ID-based operations, or {@code null} if
   * the entity has no ID at all.
   *
   * <p>Unlike {@link #getIdProperty()}, which exposes only the ID declared by this
   * entity, this method also resolves the ID from a referenced entity: an
   * {@link infra.persistence.annotation.EntityRef @EntityRef} entity without an ID of
   * its own reuses the referenced entity's ID property. Subclasses may override this
   * to resolve the ID elsewhere.
   *
   * @return the effective ID property, or {@code null} if none
   * @see #getIdProperty()
   */
  public @Nullable EntityProperty findIdProperty() {
    return idProperty;
  }

  /**
   * Return the effective ID property, failing if the entity has none.
   *
   * <p>This is the non-null variant of {@link #findIdProperty()}.
   *
   * @return the effective ID property, never {@code null}
   * @throws IllegalEntityException if the entity has no ID property
   * @see #findIdProperty()
   */
  public EntityProperty idProperty() throws IllegalEntityException {
    EntityProperty idProperty = findIdProperty();
    if (idProperty == null) {
      throw new IllegalEntityException("ID property is required");
    }
    return idProperty;
  }

  /**
   * Find the entity property with the given name.
   *
   * @param name the property name to look up
   * @return the matching property, or {@code null} if none exists
   */
  public @Nullable EntityProperty findProperty(String name) {
    return propertyMap.get(name);
  }

  /**
   * Return the merged annotations of the entity class, loading and caching them
   * on first access.
   *
   * @return the merged annotations of the entity class
   */
  public MergedAnnotations getAnnotations() {
    MergedAnnotations annotations = this.annotations;
    if (annotations == null) {
      annotations = MergedAnnotations.from(entityClass);
      this.annotations = annotations;
    }
    return annotations;
  }

  /**
   * Return the merged annotation of the given type declared on the entity class.
   *
   * @param annType the annotation type to look up
   * @return the merged annotation, or an empty annotation if not present
   */
  public <A extends Annotation> MergedAnnotation<A> getAnnotation(Class<A> annType) {
    return getAnnotations().get(annType);
  }

  /**
   * Determine whether the given annotation type is present on the entity class,
   * either directly or as a meta-annotation.
   *
   * @param annType the annotation type to check
   * @return {@code true} if the annotation is present, {@code false} otherwise
   */
  public <A extends Annotation> boolean isPresent(Class<A> annType) {
    return getAnnotations().isPresent(annType);
  }

  /**
   * Return the annotation of the given type declared on the entity class,
   * synthesized into a concrete {@link Annotation} instance that can be used
   * directly in code.
   * <p>
   * Unlike {@link #getAnnotation(Class)}, which returns a {@link MergedAnnotation},
   * this method resolves merged attribute values (including {@code @AliasFor} and
   * composed annotations) and materializes the annotation through a JDK proxy.
   * Synthesis may incur a computational cost when first invoked.
   *
   * @param annType the annotation type to synthesize
   * @param <A> the annotation type
   * @return the synthesized annotation instance
   * @throws java.util.NoSuchElementException if the annotation is not present
   * @see #getAnnotation(Class)
   * @see #isPresent(Class)
   * @since 5.0
   */
  public <A extends Annotation> A synthesizedAnnotation(Class<A> annType) {
    return getAnnotations().get(annType).synthesize();
  }

  @Override
  public String toString() {
    return ToStringBuilder.forInstance(this)
            .append("tableName", tableName)
            .append("columnNames", columnNames)
            .append("entityClass", entityClass)
            .append("idProperty", idProperty)
            .append("versionProperty", versionProperty)
            .append("entityProperties", entityProperties)
            .toString();
  }

  @Override
  public boolean equals(@Nullable Object o) {
    return this == o
            || (o instanceof EntityMetadata that && that.getClass() == getClass()
            && Objects.equals(tableName, that.tableName)
            && Objects.equals(idProperty, that.idProperty)
            && Objects.equals(versionProperty, that.versionProperty)
            && Arrays.equals(columnNames, that.columnNames)
            && Objects.equals(entityClass, that.entityClass)
            && Arrays.equals(entityProperties, that.entityProperties));
  }

  @Override
  public int hashCode() {
    int result = Objects.hash(tableName, entityClass, idProperty, versionProperty);
    result = 31 * result + Arrays.hashCode(columnNames);
    result = 31 * result + Arrays.hashCode(entityProperties);
    return result;
  }

}
