/*
 * Copyright 2017 - 2026 the TODAY authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package infra.persistence;

import org.jspecify.annotations.Nullable;

import java.lang.annotation.Annotation;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Objects;

import infra.beans.BeanMetadata;
import infra.beans.BeanProperty;
import infra.core.annotation.MergedAnnotation;
import infra.core.annotation.MergedAnnotations;
import infra.core.style.ToStringBuilder;
import infra.persistence.annotation.GeneratedId;
import infra.util.StringUtils;

/**
 * Describes the mapping between an entity class and its database representation.
 *
 * <p>It exposes the table name, the ID and version properties, the entity
 * properties together with their column names, and whether the ID is
 * auto-generated. It also provides access to the merged annotations declared on
 * the entity class.
 *
 * <p>Instances are created by an {@link EntityMetadataFactory} and are treated as
 * read-only after construction; application code should not instantiate this class
 * directly. The property lookup map and the merged annotations are cached for
 * efficient reuse.
 *
 * <p>Key features:
 * <ul>
 *   <li>Mapping between entity properties and database columns.</li>
 *   <li>Identification of auto-generated IDs.</li>
 *   <li>Merged annotation access for the entity class.</li>
 *   <li>Efficient property lookup by name.</li>
 * </ul>
 *
 * @author <a href="https://github.com/TAKETODAY">Harry Yang</a>
 * @see EntityProperty
 * @see EntityMetadataFactory
 * @since 4.0 2022/8/16 22:43
 */
public class EntityMetadata {

  /** The name of the database table backing the entity. */
  public final String tableName;

  /** The bean metadata describing the entity class. */
  public final BeanMetadata root;

  /** The entity class this metadata was created for. */
  public final Class<?> entityClass;

  /** The column name of the ID property, or {@code null} if the entity has no ID. */
  public final @Nullable String idColumnName;

  /** The ID property, or {@code null} if the entity has no ID. */
  public final @Nullable EntityProperty idProperty;

  /** The optimistic-locking version property, or {@code null} if none. */
  public final @Nullable EntityProperty versionProperty;

  /** All mapped bean properties, including the ID property. */
  public final BeanProperty[] beanProperties;

  /** Column names of {@link #entityProperties}, including the ID column. */
  public final String[] columnNames;

  /** All mapped entity properties, including the ID property. */
  public final EntityProperty[] entityProperties;

  /** Column names of {@link #entityPropertiesExcludeId}, excluding the ID column. */
  public final String[] columnNamesExcludeId;

  /** Entity properties excluding the ID property. */
  public final EntityProperty[] entityPropertiesExcludeId;

  /** Whether the ID value is generated by the database. */
  public final boolean autoGeneratedId;

  private @Nullable MergedAnnotations annotations;

  private final HashMap<String, EntityProperty> propertyMap;

  protected EntityMetadata(BeanMetadata root, Class<?> entityClass,
          @Nullable EntityProperty idProperty, String tableName, @Nullable EntityProperty versionProperty,
          List<BeanProperty> beanProperties, List<String> columnNames, List<EntityProperty> entityProperties) {
    this.root = root;
    this.tableName = tableName;
    this.idProperty = idProperty;
    this.versionProperty = versionProperty;
    this.entityClass = entityClass;
    this.propertyMap = mapProperties(entityProperties);
    this.idColumnName = idProperty != null ? idProperty.columnName : null;
    this.columnNames = StringUtils.toStringArray(columnNames);
    this.beanProperties = beanProperties.toArray(new BeanProperty[0]);
    this.entityProperties = entityProperties.toArray(new EntityProperty[0]);

    if (idProperty != null) {
      entityProperties.remove(idProperty);
      columnNames.remove(idProperty.columnName);
    }

    this.autoGeneratedId = determineGeneratedId(idProperty);
    this.columnNamesExcludeId = StringUtils.toStringArray(columnNames);
    this.entityPropertiesExcludeId = entityProperties.toArray(new EntityProperty[0]);
  }

  private HashMap<String, EntityProperty> mapProperties(List<EntityProperty> entityProperties) {
    HashMap<String, EntityProperty> propertyMap = new HashMap<>();
    for (EntityProperty property : entityProperties) {
      propertyMap.put(property.property.getName(), property);
    }
    return propertyMap;
  }

  private boolean determineGeneratedId(@Nullable EntityProperty idProperty) {
    if (idProperty != null) {
      return idProperty.isPresent(GeneratedId.class);
    }
    return false;
  }

  /**
   * Return the ID property used for ID-based operations, or {@code null} if the
   * entity has no ID. Subclasses may resolve the ID property from another entity.
   *
   * @return the effective ID property, or {@code null} if none
   */
  public @Nullable EntityProperty findIdProperty() {
    return idProperty;
  }

  /**
   * Return the ID property of the entity.
   *
   * @return the ID property, never {@code null}
   * @throws IllegalEntityException if the entity has no ID property
   */
  public EntityProperty idProperty() throws IllegalEntityException {
    EntityProperty idProperty = findIdProperty();
    if (idProperty == null) {
      throw new IllegalEntityException("ID property is required");
    }
    return idProperty;
  }

  /**
   * Find the entity property with the given name.
   *
   * @param name the property name to look up
   * @return the matching property, or {@code null} if none exists
   */
  public @Nullable EntityProperty findProperty(String name) {
    return propertyMap.get(name);
  }

  /**
   * Return the merged annotations of the entity class, loading and caching them
   * on first access.
   *
   * @return the merged annotations of the entity class
   */
  public MergedAnnotations getAnnotations() {
    MergedAnnotations annotations = this.annotations;
    if (annotations == null) {
      annotations = MergedAnnotations.from(entityClass);
      this.annotations = annotations;
    }
    return annotations;
  }

  /**
   * Return the merged annotation of the given type declared on the entity class.
   *
   * @param annType the annotation type to look up
   * @return the merged annotation, or an empty annotation if not present
   */
  public <A extends Annotation> MergedAnnotation<A> getAnnotation(Class<A> annType) {
    return getAnnotations().get(annType);
  }

  /**
   * Determine whether the given annotation type is present on the entity class,
   * either directly or as a meta-annotation.
   *
   * @param annType the annotation type to check
   * @return {@code true} if the annotation is present, {@code false} otherwise
   */
  public <A extends Annotation> boolean isPresent(Class<A> annType) {
    return getAnnotations().isPresent(annType);
  }

  @Override
  public String toString() {
    return ToStringBuilder.forInstance(this)
            .append("tableName", tableName)
            .append("columnNames", columnNames)
            .append("entityClass", entityClass)
            .append("idProperty", idProperty)
            .append("versionProperty", versionProperty)
            .append("beanProperties", beanProperties)
            .append("entityProperties", entityProperties)
            .toString();
  }

  @Override
  public boolean equals(@Nullable Object o) {
    return this == o
            || (o instanceof EntityMetadata that && that.getClass() == getClass()
            && Objects.equals(tableName, that.tableName)
            && Objects.equals(idProperty, that.idProperty)
            && Objects.equals(versionProperty, that.versionProperty)
            && Arrays.equals(columnNames, that.columnNames)
            && Objects.equals(entityClass, that.entityClass)
            && Arrays.equals(beanProperties, that.beanProperties)
            && Arrays.equals(entityProperties, that.entityProperties));
  }

  @Override
  public int hashCode() {
    int result = Objects.hash(tableName, entityClass, idProperty, versionProperty);
    result = 31 * result + Arrays.hashCode(beanProperties);
    result = 31 * result + Arrays.hashCode(columnNames);
    result = 31 * result + Arrays.hashCode(entityProperties);
    return result;
  }

}
