[[framework-home-page]]
= 首页

[horizontal]
xref:overview.adoc[概述] :: 背景, 名称, 系统要求，反馈和贡献, 鸣谢，开源协议。
xref:core.adoc[核心技术] :: IoC 容器, 事件（观察者模式）, 资源（Resources）, 国际化, Validation, 数据绑定,
类型转换, SpEL, 切面编程, AOT。
<<testing.adoc#testing, 测试>> :: Mock Objects, TestContext Framework, Web MVC Test。
xref:data-access.adoc[数据存取] :: 事物, DAO, JDBC, 自研ORM框架。
xref:web.adoc[Web 模块] :: Web 框架, WebSocket。
xref:integration.adoc[集成] :: REST 客户端, JMX, 邮件, 任务, 定时任务, 缓存, JVM Checkpoint Restore.
xref:appendix.adoc[附录] :: 附录.

Rod Johnson, Juergen Hoeller, Keith Donald, Colin Sampaleanu, Rob Harrop, Thomas Risberg,
Alef Arendsen, Darren Davison, Dmitriy Kopylenko, Mark Pollack, Thierry Templier, Erwin
Vervaet, Portia Tung, Ben Hale, Adrian Colyer, John Lewis, Costin Leau, Mark Fisher, Sam
Brannen, Ramnivas Laddad, Arjen Poutsma, Chris Beams, Tareq Abedrabbo, Andy Clement, Dave
Syer, Oliver Gierke, Rossen Stoyanchev, Phillip Webb, Rob Winch, Brian Clozel, Stephane
Nicoll, Sebastien Deleuze, Jay Bryant, Mark Paluch，海子（Harry Yang）

Copyright 2017 - 2024 the original author or authors All Rights Reserved.

Copies of this document may be made for your own use and for distribution to others,
provided that you do not charge any fee for such copies and further provided that each
copy contains this Copyright Notice, whether distributed in print or electronically.
