name: Publish Gradle Plugin
description: 'Publishes Infra App''s Gradle plugin to the Plugin Portal'
inputs:
  build-number:
    description: 'Build number to use when downloading plugin artifacts'
    required: false
    default: ${{ github.run_number }}
  gradle-plugin-publish-key:
    description: 'Gradle publishing key'
    required: true
  gradle-plugin-publish-secret:
    description: 'Gradle publishing secret'
    required: true
  plugin-version:
    description: 'Version of the plugin'
    required: true
runs:
  using: composite
  steps:
    - name: Set Up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'liberica'
        java-version: '17'
    - name: Publish
      shell: bash
      working-directory: ${{ github.action_path }}
      run: ${{ github.workspace }}/gradlew publishExisting
          -Pgradle.publish.key=${{ inputs.gradle-plugin-publish-key }}
          -Pgradle.publish.secret=${{ inputs.gradle-plugin-publish-secret }} 
          -PinfraVersion=${{ inputs.plugin-version }} 
          -PrepositoryRoot=${{ github.workspace }}/infra-build/infra-gradle-plugin
