[[expressions-ref-literal]]
= 字面量表达式

SpEL 支持以下类型的字面量表达式。

字符串 ::
  字符串可以由单引号 (`'`) 或双引号 (`"`) 分隔。
  要在由单引号包围的字符串字面量中包含单引号，请使用两个相邻的单引号字符。
  同样，要在由双引号包围的字符串字面量中包含双引号，请使用两个相邻的双引号字符。
数字 ::
  数字支持使用负号、指数符号和小数点。
  * 整数：`int` or `long`
  * 十六进制：`int` or `long`
  * 实数：`float` or `double`
  ** 默认情况下，实数使用 `Double.parseDouble()` 解析。
布尔值 ::
  `true` 或 `false`
Null ::
  `null`

[NOTE]
====
由于 Infra 表达式语言的设计和实现，字面量数字在内部始终存储为正数。

例如，`-2` 在内部存储为正 `2`，然后在评估表达式时取反（通过计算 `0 - 2` 的值）。

这意味着不可能在 Java 中表示等于该类型数字最小值的负字面量数字。
例如，Java 中 `int` 的最小支持值是 `Integer.MIN_VALUE`，其值为 `-2147483648`。
但是，如果你在 SpEL 表达式中包含 `-2147483648`，则会抛出异常，通知你无法将值 `2147483648` 解析为 `int`
（因为它超过了 `Integer.MAX_VALUE` 的值，即 `2147483647`）。

如果你需要在 SpEL 表达式中使用特定类型数字的最小值，你可以引用相应包装类型的 `MIN_VALUE` 常量
（例如 `Integer.MIN_VALUE`，`Long.MIN_VALUE` 等）或计算最小值。
例如，要使用最小整数值：

- `T(Integer).MIN_VALUE` -- 需要 `StandardEvaluationContext`
- `-2^31` -- 可与任何类型的 `EvaluationContext` 一起使用
====

以下清单显示了字面量的简单用法。通常，它们不会像这样单独使用，而是作为更复杂表达式的一部分使用——
例如，作为逻辑比较运算符一侧的字面量或作为方法的参数。

[tabs]
======
Java::
+
[source,java,indent=0,subs="verbatim,quotes",role="primary"]
----
	ExpressionParser parser = new SpelExpressionParser();

	// 评估结果为 "Hello World"
	String helloWorld = (String) parser.parseExpression("'Hello World'").getValue();

	// 评估结果为 "Tony's Pizza"
	String pizzaParlor = (String) parser.parseExpression("'Tony''s Pizza'").getValue();

	double avogadrosNumber = (Double) parser.parseExpression("6.0221415E+23").getValue();

	// 评估结果为 2147483647
	int maxValue = (Integer) parser.parseExpression("0x7FFFFFFF").getValue();

	boolean trueValue = (Boolean) parser.parseExpression("true").getValue();

	Object nullValue = parser.parseExpression("null").getValue();
----

======
