# Original Author -> Harry Yang (taketoday@foxmail.com) https://taketoday.cn
# Copyright © TODAY & 2017 - 2023 All Rights Reserved.
#
# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see [http://www.gnu.org/licenses/]

name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  deploy-snapshot:
    if: github.repository_owner == 'TAKETODAY'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17 and Maven Central Repository
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: adopt
          server-id: snapshots
          server-username: SNAPSHOTS_USERNAME
          server-password: SNAPSHOTS_TOKEN
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.7.1

      - name: Deploy snapshots
        run: ./gradlew --no-daemon publish --max-workers=4 -PrepoUsername=$SNAPSHOTS_USERNAME \
            -PrepoPassword=$SNAPSHOTS_TOKEN -Psigning.keyId=$SIGNID -Psigning.password=$SIGNPWD
        env:
          SNAPSHOTS_TOKEN: ${{ secrets.SNAPSHOTS_TOKEN }}
          SNAPSHOTS_USERNAME: ${{ secrets.SNAPSHOTS_USERNAME }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
          SIGNID: ${{secrets.SIGNID}}
          SIGNPWD: ${{secrets.SIGNPWD}}
