name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  deploy-snapshot:
    if: github.repository_owner == 'TAKETODAY'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4

      - name: Read Version
        id: read-version
        uses: ./.github/actions/read-version

      - name: Deploy snapshot
        if: ${{ steps.read-version.outputs.snapshot == 'true' }}
        uses: ./.github/actions/building
        with:
          java-version: 17
          publish: true
          signing-keyId: ${{ secrets.SIGNID }}
          signing-password: ${{ secrets.SIGNPWD }}
          token-username: ${{ secrets.SNAPSHOTS_USERNAME }}
          token-password: ${{ secrets.SNAPSHOTS_TOKEN }}
          gpg-passphrase: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}

