# Original Author -> Harry Yang (taketoday@foxmail.com) https://taketoday.cn
# Copyright © TODAY & 2017 - 2023 All Rights Reserved.
#
# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see [http://www.gnu.org/licenses/]

name: GitHub CI

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ macOS-latest, windows-latest, ubuntu-latest ]
        # os: [ macOS-latest, ubuntu-latest ]
        os: [ ubuntu-latest ]

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17 and Maven Central Repository
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: adopt
          server-id: snapshots
          server-username: ${{ secrets.SNAPSHOTS_USERNAME }}
          server-password: ${{ secrets.SNAPSHOTS_TOKEN }}
          gpg-passphrase: ${{ secrets.MAVEN_GPG_PASSPHRASE }} # gpg短密码环境变量
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }} # gpg私钥
      - name: Set argLine command line option
        run: echo 'ARG_LINE=-D"argLine=--illegal-access=permit"' >> $GITHUB_ENV

      - name: Publish SNAPSHOT
        run: mvn --batch-mode deploy -P release -B -D"license.skip=true" -D"jacoco.skip=true" $ARG_LINE