name: CI

on:
  push:
    branches: [ master ]

jobs:
  deploy-snapshot:
    if: github.repository_owner == 'TAKETODAY'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macOS-latest, windows-latest ]
        java: [ 20, 21 ]
      fail-fast: false
      max-parallel: 4
    name: JDK ${{ matrix.java }} on ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Set JDK from jdk.java.net
        uses: oracle-actions/setup-java@v1
        with:
          website: jdk.java.net
          release: ${{ matrix.java }}

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: adopt
          cache: 'maven'

      - name: Build with Maven
        run: mvn -B package -DCI=true
