name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    if: github.repository_owner == 'TAKETODAY'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macOS-latest ] #, windows-latest
        java: [ 17, 21 ]
      fail-fast: false
      max-parallel: 4
    name: JDK ${{ matrix.java }} on ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Set JDK ${{ matrix.java }} from jdk.java.net
        uses: oracle-actions/setup-java@v1
        with:
          website: jdk.java.net
          release: ${{ matrix.java }}
        if: ${{ matrix.java != '17' }}
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: zulu
        if: ${{ matrix.java == '17' }}
      - name: Print JDK Version
        run: java -version

      - name: Build with Gradle
        run: ./gradlew -DCI=true --no-daemon --max-workers=4 check
