name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    if: github.repository_owner == 'TAKETODAY'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macOS-latest, windows-latest ]
      fail-fast: false
      max-parallel: 4
    name: JDK ${{ matrix.java }} on ${{ matrix.os }}

    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3

      - name: Setup JDK 21
        uses: oracle-actions/setup-java@v1
        with:
          website: jdk.java.net
          release: 21

      - name: Print JDK Version
        run: java -version

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.7.1

      - name: Build with Gradle
        run: ./gradlew -DCI=true --no-daemon --max-workers=4 check
