name: CI

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master
      - 'dev/**'
      - 'fix/**'
      - 'feat/**'
      - 'feature/**'

jobs:
  check:
    if: github.repository_owner == 'TAKETODAY'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macOS-latest ] #, windows-latest
        java: [ 21 ]
      fail-fast: false
      max-parallel: 4
    name: JDK ${{ matrix.java }} on ${{ matrix.os }}

    steps:
      - name: Fix Git Config
        run: git config --system core.longpaths true
        if: ${{ matrix.os == 'windows-latest' }}

      - name: Checkout project sources
        uses: actions/checkout@v4.1.2

      - name: Setup JDK 21
        uses: actions/setup-java@v4.2.1
        with:
          java-version: ${{ matrix.java }}
          distribution: adopt

      - name: Print JDK Version
        run: java -version

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3.1.0

      - name: Build with Gradle
        run: ./gradlew -DCI=true --no-daemon --max-workers=4 build --scan --stacktrace
